#!/usr/bin/env python3
"""Cedar Press 1161 - IS THIS MONEY COLUMN SUMMABLE? Measured, per column.

    py -3 code/1161_money_column_summability.py report
    py -3 code/1161_money_column_summability.py apply
    py -3 code/1161_money_column_summability.py verify

-------------------------------------------------------------------------------
THE QUESTION
-------------------------------------------------------------------------------
Owner, 2026-09-02, on what only a full-data check can answer: *"transaction
totals versus cumulative snapshots are additive"* - i.e. whether they can be
summed at all. The ten-row customer review put it concretely: *"Contract
transactions carry changing cumulative award totals that cannot be summed."*

A money column in this product is one of four different things and the column
name does not say which:

  TRANSACTION_ADDITIVE        one row = one movement of money. SUM(col) is the
                              answer (subject to any named row filter).
  SNAPSHOT_RESTATED_PER_ROW   an award- or entity-level figure copied onto
                              every row of its group. SUM(col) multiplies it by
                              the group size. The answer is one value per group.
  CUMULATIVE_RESTATED_PER_ROW an award-to-date running total, so it CHANGES per
                              row and still may not be summed. The answer is the
                              LAST value per group.
  ADDITIVE_WITHIN_GROUP       varies per row and is not a running total: the
                              rows genuinely partition the group.

A fifth appears when a figure is restated per row and no column orders the
group: RESTATED_PER_ROW_WITH_DRIFT, where the group's MAXIMUM stands in for its
last value.

**A constancy test alone does not find the worst of these.** It finds
SNAPSHOT_RESTATED_PER_ROW, and it walks straight past a ceiling that FALLS on a
de-obligation - which is exactly what `contractors.total_award_value` does. Nor
does monotonicity: only 9,927 of its 132,976 multi-row award groups only ever
rise. The statistic that separates them is AUTOCORRELATION: inside one award,
successive values of a restated figure differ by 30% on average, and successive
values of a genuine per-transaction amount differ by 97%. Measured on the
delivered files the two populations do not overlap - see AUTOCORRELATION_MAX
below, which carries the eight figures behind the threshold.

Every figure here is MEASURED on the delivered file and never typed into a
dict, for the reason `cedar_publication.subaward_warning()` is measured on every
build: the constant moves, and a typed constant goes stale silently.

-------------------------------------------------------------------------------
WHAT IS DECLARED AND WHAT IS MEASURED
-------------------------------------------------------------------------------
DECLARED (a human must state these; a machine cannot guess them):
  * which columns hold money,
  * which column is the GROUP the figure belongs to (the award key, the entity
    key), and
  * which column ORDERS rows inside that group.
Everything else - constancy, monotonicity, the verdict, the overstatement
factor, the correct total - is measured.

A declared group key that resolves on only part of the column does NOT make the
column unmeasurable - it makes the verdict a statement about the keyed SUBSET,
and the verdict says so, with the share and the row counts. Refusing outright
was the first draft's behaviour and it silently dropped every contractors
column, because `contract_award_unique_key` is blank on 376,766 of the
1,217,768 delivered rows (the pre-USAspending archive vintage). A key that
resolves on NO row is still refused: there is nothing to measure.

-------------------------------------------------------------------------------
WHERE THE ANSWER GOES
-------------------------------------------------------------------------------
  docs/MONEY_COLUMN_SUMMABILITY.json   machine-readable, regenerated by `apply`.
                                       One object per (dataset, column) with the
                                       verdict, the two totals and the factor.
  docs/MONEY_TOTALLING_RULES.md        the governing document, inside
                                       <!-- BEGIN COLUMN-SUMMABILITY-1161 --> /
                                       <!-- END COLUMN-SUMMABILITY-1161 -->.
                                       That file is written WHOLESALE by
                                       `code/574_ws1_money_and_conservation.py`,
                                       which preserves only marked blocks.

`summability_warning(dataset, column)` returns the one sentence a document or a
codebook may print, with its denominator stated. Import it; do not retype a
number out of the markdown.

-------------------------------------------------------------------------------
VERIFY FAILS WHEN THE WORK DID NOT LAND
-------------------------------------------------------------------------------
Not a conservation check. `verify` asserts the INTENDED delta:
  V1  docs/MONEY_COLUMN_SUMMABILITY.json exists and covers every declared
      column that is present in the delivered files.
  V2  at least MIN_NEVER_SUM columns carry a never-sum verdict - a run that
      found none of the known-bad columns has measured the wrong thing.
  V3  prime_contracts `total_award_value` is one of them, with a factor above
      2.0. This is the customer-visible instance the review named; if the
      measurement stops seeing it, the measurement is broken.
  V4  the marked block is present in docs/MONEY_TOTALLING_RULES.md and names
      the same factor as the JSON, to the same rounding.
"""

import csv
import json
import math
import sys
from collections import defaultdict
from datetime import date
from pathlib import Path

CEDAR = Path(__file__).resolve().parent.parent
DIST = CEDAR / "dist" / "customer"
DOCS = CEDAR / "docs"
JSON_OUT = DOCS / "MONEY_COLUMN_SUMMABILITY.json"
RULES_MD = DOCS / "MONEY_TOTALLING_RULES.md"
BEGIN = "<!-- BEGIN COLUMN-SUMMABILITY-1161 -->"
END = "<!-- END COLUMN-SUMMABILITY-1161 -->"
TODAY = date.today().isoformat()

csv.field_size_limit(min(sys.maxsize, 2**31 - 1))

# Fraction of multi-row groups that must agree before a shape is declared.
CONSTANT_THRESHOLD = 0.95
# Within-group spread, (max-min)/max, under which a group counts as restated
# rather than partitioned. FSRS primes restate a revised prime award amount in a
# later report; that is a correction to one figure, not a second figure.
NEAR_CONSTANT_DRIFT = 0.02
# `mean_distinct_value_ratio` (distinct values / rows, per multi-row group) is
# REPORTED and is not decisive: it does not separate a running total, which
# carries a distinct value on most rows, from a partition, which does the same.
#
# THE DECISIVE STATISTIC. Mean, over multi-row groups, of the average relative
# step |v(i) - v(i-1)| / max(|v(i)|, |v(i-1)|) between successive values ordered
# by the group's own date column. A figure being RESTATED moves in small steps
# off a large base; independent per-row amounts do not. Measured 2026-09-02 on
# the delivered files, the two populations do not overlap and are not close:
#
#   RESTATED   subcontracting.prime_award_amount            0.010
#              funding.total_face_value_of_loan             0.000
#              contractors.total_award_value                0.304
#              contractors.total_award_value_real2025       0.319
#   ADDITIVE   funding.obligated_usd_real2025               0.761
#              funding.obligated_usd                        0.767
#              contractors.total_obligations_real2025       0.967
#              contractors.total_obligations                0.970
#
# The threshold sits in the empty band between 0.319 and 0.761. Re-read those
# figures out of the report before moving it; a threshold tuned to one build is
# the failure this repo has twenty-four instances of.
AUTOCORRELATION_MAX = 0.50
# Below this share of rows carrying a value, the group key does not resolve on
# the whole column and the verdict is reported as covering the keyed SUBSET.
KEY_COVERAGE_FLOOR = 0.90

MIN_NEVER_SUM = 8

NEVER_SUM = ("SNAPSHOT_RESTATED_PER_ROW", "CUMULATIVE_RESTATED_PER_ROW",
             "RESTATED_PER_ROW_WITH_DRIFT")


# ---------------------------------------------------------------------------
# DECLARED: the money columns, their group, and what orders the group.
# ---------------------------------------------------------------------------
# group_key None  -> the row IS the grain; there is nothing to restate onto.
# order_key None  -> monotonicity is not tested (reported as not_applicable).
SPEC = [
    # ---- contractors (prime_contracts) -----------------------------------
    ("contractors.csv", "total_obligations", "contract_award_unique_key", "action_date"),
    ("contractors.csv", "total_award_value", "contract_award_unique_key", "action_date"),
    ("contractors.csv", "total_obligations_real2025", "contract_award_unique_key", "action_date"),
    ("contractors.csv", "total_award_value_real2025", "contract_award_unique_key", "action_date"),
    # ---- funding (federal assistance) ------------------------------------
    ("funding.csv", "obligated_usd", "assistance_award_unique_key", "action_date"),
    ("funding.csv", "obligated_usd_real2025", "assistance_award_unique_key", "action_date"),
    ("funding.csv", "face_value_of_loan", "assistance_award_unique_key", "action_date"),
    ("funding.csv", "original_loan_subsidy_cost", "assistance_award_unique_key", "action_date"),
    ("funding.csv", "total_face_value_of_loan", "assistance_award_unique_key", "action_date"),
    ("funding.csv", "total_loan_subsidy_cost", "assistance_award_unique_key", "action_date"),
    # a rollup table joined onto every transaction row of its entity
    ("funding.csv", "bie_uio_dollars_by_entity__total_usd",
     "bie_uio_dollars_by_entity__tribe_id", None),
    ("funding.csv", "bie_uio_dollars_by_entity__usd_prime_contracts",
     "bie_uio_dollars_by_entity__tribe_id", None),
    ("funding.csv", "bie_uio_dollars_by_entity__usd_subawards",
     "bie_uio_dollars_by_entity__tribe_id", None),
    # ---- subcontracting --------------------------------------------------
    ("subcontracting.csv", "subaward_amount", None, None),
    ("subcontracting.csv", "subaward_amount_real2025", None, None),
    ("subcontracting.csv", "prime_award_amount", "prime_award_unique_key", "subaward_date"),
    ("subcontracting.csv", "subaward_entity_rollup__usd_as_prime_a",
     "subaward_entity_rollup__tribe_id", None),
    ("subcontracting.csv", "subaward_entity_rollup__usd_as_subawardee_b",
     "subaward_entity_rollup__tribe_id", None),
    ("subcontracting.csv", "subaward_entity_rollup__usd_both_sides",
     "subaward_entity_rollup__tribe_id", None),
    # ---- lobbying --------------------------------------------------------
    ("lobbying.csv", "income_usd", "filing_uuid", None),
    ("lobbying.csv", "expenses_usd", "filing_uuid", None),
    ("lobbying.csv", "spend_usd", "filing_uuid", None),
    # ---- natural resources ----------------------------------------------
    ("natural-resources.csv", "amount_usd", None, None),
    ("natural-resources.csv", "amount_usd_real2025", None, None),
    # ---- nonprofits (BMF entity snapshot, one filing period) -------------
    ("nonprofits.csv", "bmf_revenue_amt", "EIN", None),
    ("nonprofits.csv", "bmf_income_amt", "EIN", None),
    ("nonprofits.csv", "bmf_asset_amt", "EIN", None),
    # ---- deals -----------------------------------------------------------
    ("deals.csv", "Announced_Value_USD", "Deal_ID", None),
    ("deals.csv", "Project_Total_Value_USD", "Deal_ID", None),
]

# Row filters a buyer must apply BEFORE summing an additive column. These are
# not measured here - they are owned by the modules named - but the verdict is
# useless without pointing at them, so each is named beside its column.
FILTER_NOTE = {
    ("subcontracting.csv", "subaward_amount"):
        "and only over rows with duplicate_status == 'primary' AND "
        "subaward_exceeds_prime_flag != 'yes' - see "
        "cedar_publication.subaward_warning()",
    ("subcontracting.csv", "subaward_amount_real2025"):
        "the same filter as subaward_amount",
    ("lobbying.csv", "spend_usd"):
        "and only over rows whose supersession_status is not a SUPERSEDED_* or "
        "AMBIGUOUS_* value and whose attribution_withdrawn != 1 - see "
        "cedar_publication.lobbying_warning()",
    ("natural-resources.csv", "amount_usd"):
        "and read amount_sign_meaning and aggregation_level first: a row whose "
        "aggregation_level is not the transaction level is itself a rollup",
    ("lobbying.csv", "income_usd"):
        "and NEVER together with expenses_usd - an LDA filing reports income "
        "(a registrant billing a client) OR expenses (a client self-filing), "
        "and spend_usd is the coalesced one. Adding the two double-counts; "
        "adding either to spend_usd double-counts",
    ("lobbying.csv", "expenses_usd"):
        "and NEVER together with income_usd - see income_usd",
    ("deals.csv", "Announced_Value_USD"):
        "and read Value_Type first: the column holds several different kinds of "
        "figure and summing across them adds unlike things",
    ("deals.csv", "Project_Total_Value_USD"):
        "and never together with Announced_Value_USD on the same deal - the "
        "project total CONTAINS the announced value",
}

# Columns whose NAME says the opposite of what the measurement found. A buyer
# reads the name, not this file, so each one is stated in the doc block.
NAME_WARNING = {
    ("contractors.csv", "total_obligations"):
        "the name says TOTAL and the column is a per-TRANSACTION delta - it "
        "carries negative values on de-obligations and sums correctly to the "
        "award total. It is the USAspending `federal_action_obligation`, "
        "renamed. Summing it is right; reading one row of it as an award total "
        "is wrong",
    ("contractors.csv", "total_award_value"):
        "sits one column away from total_obligations, is named the same way, "
        "and behaves in the opposite way: it is the award-to-date ceiling "
        "restated on every transaction",
}


def out(s=""):
    sys.stdout.write(str(s).encode("ascii", "replace").decode() + "\n")


def money(raw):
    """Parse a delivered money cell. Returns None when it is not a number."""
    s = (raw or "").strip().replace(",", "").replace("$", "")
    if not s or s in ("-", "NA", "N/A", "None", "nan", "NaN"):
        return None
    neg = s.startswith("(") and s.endswith(")")
    if neg:
        s = s[1:-1]
    try:
        v = float(s)
    except ValueError:
        return None
    if math.isnan(v) or math.isinf(v):
        return None
    return -v if neg else v


# ---------------------------------------------------------------------------
# measurement
# ---------------------------------------------------------------------------
def measure_file(fname, specs):
    """One streaming pass over one delivered file for every column declared on it."""
    path = DIST / fname
    if not path.exists():
        return {c: {"status": "UNMEASURED",
                    "reason": f"{fname} is not in dist/customer"} for _, c, _, _ in specs}

    with path.open(encoding="utf-8-sig", errors="replace", newline="") as fh:
        rd = csv.reader(fh)
        header = next(rd)
        idx = {h: i for i, h in enumerate(header)}

        live, results = [], {}
        for _, col, gk, ok in specs:
            if col not in idx:
                results[col] = {"status": "UNMEASURED",
                                "reason": f"column absent from {fname}"}
                continue
            if gk is not None and gk not in idx:
                results[col] = {"status": "UNMEASURED",
                                "reason": f"declared group key {gk} absent from {fname}"}
                continue
            live.append((col, gk, ok))
        if not live:
            return results

        # Per column the groups hold the FULL list of (order, value) pairs, not a
        # running summary. A single forward pass cannot judge monotonicity,
        # because the delivered file is not sorted by (group, date) - an earlier
        # attempt that tried refused 100% of the groups as "out of order", which
        # is a clean-looking result about nothing. The lists are sorted per group
        # afterwards, so the answer does not depend on the file's row order.
        n_rows = 0
        agg = {}
        for col, gk, ok in live:
            agg[col] = {"n_val": 0, "sum": 0.0, "n_keyed": 0,
                        "groups": defaultdict(list)}

        for row in rd:
            n_rows += 1
            for col, gk, ok in live:
                try:
                    v = money(row[idx[col]])
                except IndexError:
                    continue
                if v is None:
                    continue
                a = agg[col]
                a["n_val"] += 1
                a["sum"] += v
                if gk is None:
                    continue
                key = (row[idx[gk]] or "").strip()
                if not key:
                    continue
                a["n_keyed"] += 1
                a["groups"][key].append(
                    ((row[idx[ok]] or "").strip() if ok else "", v))

    for col, gk, ok in live:
        a = agg[col]
        r = {"status": "MEASURED", "rows_in_file": n_rows,
             "rows_with_value": a["n_val"], "sum_all_rows": a["sum"],
             "group_key": gk, "order_key": ok}
        if a["n_val"] == 0:
            r["status"] = "UNMEASURED"
            r["reason"] = "no parseable numeric value in any row"
            results[col] = r
            continue
        if gk is None:
            r["verdict"] = "TRANSACTION_ADDITIVE"
            r["verdict_basis"] = ("no group key is declared: the delivered row IS "
                                  "the grain, so there is nothing for the figure "
                                  "to be restated onto")
            r["correct_total"] = a["sum"]
            r["factor_if_summed"] = 1.0
            results[col] = r
            continue

        cov = a["n_keyed"] / a["n_val"]
        r["group_key_coverage"] = round(cov, 4)
        if a["n_keyed"] == 0:
            r["status"] = "UNMEASURED"
            r["reason"] = (f"declared group key {gk} is blank on every one of the "
                           f"{a['n_val']:,} rows carrying a value")
            results[col] = r
            continue
        # A group key that does not resolve on every row does NOT make the column
        # unmeasurable - it makes the verdict a statement about the keyed subset.
        # Saying so, with the share, beats both a refusal and a silent extension
        # to rows the key never reached.
        subset = cov < KEY_COVERAGE_FLOOR
        if subset:
            r["measured_on"] = (
                f"the {a['n_keyed']:,} of {a['n_val']:,} rows "
                f"({100.0 * cov:.1f}%) on which {gk} resolves; the remaining "
                f"{a['n_val'] - a['n_keyed']:,} rows carry no award key and are "
                f"NOT covered by this verdict")

        groups = a["groups"]
        n_g = len(groups)
        keyed_sum = 0.0
        sum_max = sum_last = 0.0
        n_m = const = near_const = mono = 0
        dvr_num = step_num = ramp_num = 0.0
        n_step = 0
        for pairs in groups.values():
            vals = [v for _, v in pairs]
            keyed_sum += sum(vals)
            mx = max(vals)
            sum_max += mx
            pairs_sorted = sorted(pairs, key=lambda p: p[0])
            sum_last += pairs_sorted[-1][1]
            if len(vals) == 1:
                continue
            n_m += 1
            uniq = set(vals)
            if len(uniq) == 1:
                const += 1
                near_const += 1
            else:
                mn = min(vals)
                if mx and abs(mx - mn) / abs(mx) <= NEAR_CONSTANT_DRIFT:
                    near_const += 1
                svals = [v for _, v in pairs_sorted]
                if all(b >= a2 for a2, b in zip(svals, svals[1:])):
                    mono += 1
            dvr_num += len(uniq) / len(vals)
            # AUTOCORRELATION, the statistic that tells a running total from a
            # partition. A restated figure moves in small steps off a large
            # base; independent per-row amounts do not. The two are otherwise
            # numerically identical - both give group_max / group_sum ~ 1/n -
            # which is why a constancy test alone misses a ceiling that FALLS on
            # a de-obligation. `total_award_value` is exactly that column.
            svals = [v for _, v in pairs_sorted]
            steps = [abs(b - a2) / max(abs(a2), abs(b))
                     for a2, b in zip(svals, svals[1:]) if max(abs(a2), abs(b)) > 0]
            if steps:
                step_num += sum(steps) / len(steps)
                n_step += 1
            mean_abs = sum(abs(x) for x in vals) / len(vals)
            if mean_abs > 0:
                ramp_num += abs(mx) / mean_abs
        dvr = dvr_num / n_m if n_m else None
        mean_step = step_num / n_step if n_step else None
        mean_ramp = ramp_num / n_m if n_m else None

        r.update({"n_groups": n_g, "n_multirow_groups": n_m,
                  "n_multirow_constant": const,
                  "n_multirow_near_constant": near_const,
                  "n_multirow_monotone_nondecreasing_not_constant": mono,
                  "mean_distinct_value_ratio": round(dvr, 4) if dvr is not None else None,
                  "mean_relative_step": round(mean_step, 4) if mean_step is not None else None,
                  "mean_max_over_mean": round(mean_ramp, 4) if mean_ramp is not None else None,
                  "sum_over_keyed_rows": keyed_sum,
                  "sum_of_group_max": sum_max, "sum_of_group_last": sum_last})
        base = keyed_sum if subset else a["sum"]
        r["sum_judged"] = base

        if n_m == 0:
            r["verdict"] = "TRANSACTION_ADDITIVE"
            r["verdict_basis"] = (f"every one of the {n_g:,} `{gk}` groups holds exactly "
                                  f"one row, so the delivered row is the grain")
            r["correct_total"] = base
        elif near_const / n_m >= CONSTANT_THRESHOLD:
            r["verdict"] = "SNAPSHOT_RESTATED_PER_ROW"
            r["verdict_basis"] = (
                f"{const:,} of {n_m:,} multi-row `{gk}` groups "
                f"({100.0 * const / n_m:.1f}%) hold ONE value repeated on every row, "
                f"and {near_const:,} ({100.0 * near_const / n_m:.1f}%) vary by no more "
                f"than {100 * NEAR_CONSTANT_DRIFT:.0f}%: an award- or entity-level "
                f"figure restated per row, which summing multiplies by the group size")
            r["correct_total"] = sum_max
        elif mean_step is not None and mean_step <= AUTOCORRELATION_MAX and ok:
            r["verdict"] = "CUMULATIVE_RESTATED_PER_ROW"
            r["verdict_basis"] = (
                f"inside a `{gk}` group, successive values ordered by `{ok}` differ by "
                f"only {100.0 * mean_step:.1f}% on average (threshold "
                f"{100.0 * AUTOCORRELATION_MAX:.0f}%), and {const:,} of {n_m:,} groups "
                f"({100.0 * const / n_m:.1f}%) never move at all: the column is ONE "
                f"award-level figure restated on each transaction - a running total or "
                f"a ceiling - not a per-row amount. "
                + (f"{mono:,} groups ({100.0 * mono / n_m:.1f}%) only ever rise; the "
                   f"rest fall on de-obligations, which is why a monotonicity test "
                   f"alone does not find this column" if mono else
                   "no group is monotone non-decreasing"))
            r["correct_total"] = sum_last
        elif mean_step is not None and mean_step <= AUTOCORRELATION_MAX:
            r["verdict"] = "RESTATED_PER_ROW_WITH_DRIFT"
            r["verdict_basis"] = (
                f"inside a `{gk}` group, successive values differ by only "
                f"{100.0 * mean_step:.1f}% on average and {const:,} of {n_m:,} groups "
                f"({100.0 * const / n_m:.1f}%) never move at all, so the figure is "
                f"restated per row rather than partitioned across them; no order "
                f"column is declared for this group, so the group's MAXIMUM is used "
                f"rather than its last value")
            r["correct_total"] = sum_max
        else:
            r["verdict"] = "ADDITIVE_WITHIN_GROUP"
            r["verdict_basis"] = (
                f"successive values inside a `{gk}` group differ by "
                f"{100.0 * (mean_step or 1):.1f}% on average - far above the "
                f"{100.0 * AUTOCORRELATION_MAX:.0f}% at which a column is one figure "
                f"being restated - and only {const:,} of {n_m:,} groups are constant: "
                f"the rows partition the group rather than restate it, so SUM is the "
                f"answer")
            r["correct_total"] = base
        ct = r["correct_total"]
        r["factor_if_summed"] = round(base / ct, 4) if ct else None
        results[col] = r
    return results


def measure_all():
    by_file = defaultdict(list)
    for s in SPEC:
        by_file[s[0]].append(s)
    out = {}
    for fname in sorted(by_file):
        sys.stdout.write(f"  measuring {fname} ...\n")
        sys.stdout.flush()
        for col, res in measure_file(fname, by_file[fname]).items():
            res["dataset"] = fname
            res["column"] = col
            note = FILTER_NOTE.get((fname, col))
            if note:
                res["row_filter"] = note
            warn = NAME_WARNING.get((fname, col))
            if warn:
                res["name_warning"] = warn
            out[f"{fname}::{col}"] = res
    return out


# ---------------------------------------------------------------------------
# the sentence a document may print
# ---------------------------------------------------------------------------
def _load():
    if not JSON_OUT.exists():
        return {}
    return json.loads(JSON_OUT.read_text(encoding="utf-8")).get("columns", {})


def summability_warning(dataset, column, measured=None):
    """One sentence, with its denominator stated. Never retype this."""
    m = (measured or _load()).get(f"{dataset}::{column}")
    if not m:
        return (f"`{column}` in `{dataset}` has NOT been measured for "
                f"summability. Do not total it until "
                f"`py -3 code/1161_money_column_summability.py apply` has run.")
    if m.get("status") != "MEASURED":
        return (f"`{column}` in `{dataset}`: UNMEASURED - {m.get('reason','no reason recorded')}. "
                f"Do not total it.")
    v = m["verdict"]
    scope = (" " + m["measured_on"]) if m.get("measured_on") else ""
    if v == "TRANSACTION_ADDITIVE":
        return (f"`{column}` in `{dataset}` is TRANSACTION-ADDITIVE: sum it over rows "
                f"{m.get('row_filter', '(no row filter recorded)')}. "
                f"{m['rows_with_value']:,} rows total ${m['sum_all_rows']:,.2f}. "
                f"{m['verdict_basis']}.")
    if v == "ADDITIVE_WITHIN_GROUP":
        return (f"`{column}` in `{dataset}` partitions its group "
                f"(`{m['group_key']}`) rather than restating it, so SUM is the "
                f"answer: {m['rows_with_value']:,} rows total ${m['sum_all_rows']:,.2f}. "
                f"{m['verdict_basis']}"
                + (f". Measured on{scope}" if scope else "") + ".")
    correct = m["correct_total"]
    fac = m["factor_if_summed"]
    how = {"CUMULATIVE_RESTATED_PER_ROW": "the LAST value per ",
           }.get(v, "one value per ")
    return (f"`{column}` in `{dataset}` MUST NOT BE SUMMED: {m['verdict_basis']}. "
            f"Summing gives ${m['sum_judged']:,.2f}, which is "
            f"{fac:,.2f}x the correct ${correct:,.2f} taken as {how}"
            f"`{m['group_key']}` over {m['n_groups']:,} groups"
            + (f", measured on{scope}" if scope else "") +
            ". Measured from the delivered file, not quoted.")


# ---------------------------------------------------------------------------
def render_block(measured):
    L = [BEGIN,
         "## Per-column summability, measured on the delivered files "
         f"(workstream COLUMN-SUMMABILITY, `code/1161_money_column_summability.py`, {TODAY})",
         "",
         "*Owner, 2026-09-02, on what only a full-data check can answer: "
         "\"transaction totals versus cumulative snapshots are additive\" - i.e. "
         "whether they can be summed at all. This block answers it per column. "
         "Every figure is re-measured from `dist/customer/` by "
         "`py -3 code/1161_money_column_summability.py apply`; the machine-readable "
         "form is `docs/MONEY_COLUMN_SUMMABILITY.json` and the sentence to print is "
         "`1161.summability_warning(dataset, column)`. Do not retype a number out of "
         "this table.*",
         "",
         "*This file is written WHOLESALE by `code/574_ws1_money_and_conservation.py`, "
         "which preserves only marked blocks; this section lives inside a marked block "
         "named COLUMN-SUMMABILITY-1161 and no other block was touched. The marker "
         "literals are deliberately NOT repeated in this sentence - an earlier draft "
         "quoted them, and the writer's own search for the END marker then found the "
         "quote instead and truncated the block on rewrite.*",
         "",
         "**The four shapes.** `TRANSACTION_ADDITIVE` - one row is one movement of "
         "money, SUM is the answer. `ADDITIVE_WITHIN_GROUP` - the rows partition "
         "their group, SUM is the answer. `SNAPSHOT_RESTATED_PER_ROW` - an award- or "
         "entity-level figure copied onto every row of its group; SUM multiplies it "
         "by the group size. `CUMULATIVE_RESTATED_PER_ROW` - an award-to-date running "
         "total, so it CHANGES per row and still may not be summed; the answer is the "
         "last value per group. The last two are the ones a column name never warns "
         "you about.",
         "",
         "| dataset | column | verdict | rows | SUM(all rows) | correct total | factor if summed |",
         "|---|---|---|---:|---:|---:|---:|"]
    for k in sorted(measured):
        m = measured[k]
        if m.get("status") != "MEASURED":
            L.append(f"| `{m['dataset']}` | `{m['column']}` | **UNMEASURED** | | | | "
                     f"{m.get('reason','')} |")
            continue
        flag = ("**NEVER SUM** (" + m["verdict"] + ")" if m["verdict"] in NEVER_SUM
                else m["verdict"])
        star = " *" if m.get("measured_on") else ""
        L.append(f"| `{m['dataset']}` | `{m['column']}` | {flag}{star} | "
                 f"{m['rows_with_value']:,} | "
                 f"${m.get('sum_judged', m['sum_all_rows']):,.2f} | "
                 f"${m['correct_total']:,.2f} | "
                 f"{m['factor_if_summed']:,.2f}x |")
    L += ["", "### Every never-sum column, in one sentence each", ""]
    for k in sorted(measured):
        m = measured[k]
        if m.get("status") == "MEASURED" and m["verdict"] in NEVER_SUM:
            L.append(f"* {summability_warning(m['dataset'], m['column'], measured)}")
    L += ["", "### Where a row filter applies before summing", ""]
    for k in sorted(measured):
        m = measured[k]
        if m.get("row_filter"):
            L.append(f"* `{m['dataset']}` `{m['column']}` - {m['row_filter']}.")
    warned = [measured[k] for k in sorted(measured) if measured[k].get("name_warning")]
    if warned:
        L += ["", "### Where the column NAME says the opposite of the measurement", ""]
        for m in warned:
            L.append(f"* `{m['dataset']}` `{m['column']}` - {m['name_warning']}.")
    blank = [measured[k] for k in sorted(measured)
             if measured[k].get("status") != "MEASURED"
             and "no parseable numeric value" in (measured[k].get("reason") or "")]
    if blank:
        L += ["", "### Declared money columns that are EMPTY in the delivered file", "",
              "Not a summability verdict - a delivery finding. These columns reach the "
              "customer file with a header and no value on any row.", ""]
        for m in blank:
            L.append(f"* `{m['dataset']}` `{m['column']}` - "
                     f"{m.get('rows_in_file', 0):,} rows, none parseable as a number.")
    starred = [measured[k] for k in sorted(measured) if measured[k].get("measured_on")]
    if starred:
        L += ["", "### `*` - a verdict measured on a SUBSET, and which subset", ""]
        for m in starred:
            L.append(f"* `{m['dataset']}` `{m['column']}` - measured on "
                     f"{m['measured_on']}.")
    L += ["",
          "**What is DECLARED and what is MEASURED.** Which columns hold money, "
          "which column is the group the figure belongs to, and which column orders "
          "that group are declared in `1161.SPEC` - a machine cannot guess them. "
          "Constancy, monotonicity, the verdict, the two totals and the factor are "
          "all measured. A declared group key that is blank on more than "
          f"{100 * (1 - KEY_COVERAGE_FLOOR):.0f}% of the rows carrying a value is "
          "REFUSED and reported UNMEASURED rather than producing a clean verdict "
          "about nothing.",
          END]
    return "\n".join(L)


def write_block(text):
    md = RULES_MD.read_text(encoding="utf-8")
    if BEGIN in md and END in md:
        # rindex, not index: if any prose inside the block ever quotes the end
        # marker, index() finds the quote and the rewrite truncates the block.
        a, b = md.index(BEGIN), md.rindex(END) + len(END)
        md = md[:a] + text + md[b:]
    else:
        md = md.rstrip("\n") + "\n\n" + text + "\n"
    RULES_MD.write_text(md, encoding="utf-8", newline="\n")


# ---------------------------------------------------------------------------
def cmd_report(apply_it=False):
    out(f"1161 money-column summability - {TODAY}")
    out("=" * 78)
    measured = measure_all()
    out("")
    hdr = f"{'dataset':24s} {'column':44s} {'verdict':30s} {'factor':>9s}"
    out(hdr)
    out("-" * len(hdr))
    never = []
    for k in sorted(measured):
        m = measured[k]
        if m.get("status") != "MEASURED":
            out(f"{m['dataset']:24s} {m['column']:44s} {'UNMEASURED':30s} "
                f"        - {m.get('reason','')[:60]}")
            continue
        if m["verdict"] in NEVER_SUM:
            never.append(m)
        out(f"{m['dataset']:24s} {m['column']:44s} {m['verdict']:30s} "
            f"{m['factor_if_summed']:>8,.2f}x  "
            f"step={m.get('mean_relative_step')} dvr={m.get('mean_distinct_value_ratio')} "
            f"ramp={m.get('mean_max_over_mean')} const={m.get('n_multirow_constant')}"
            f"/{m.get('n_multirow_groups')} mono={m.get('n_multirow_monotone_nondecreasing_not_constant')}")
    out("")
    out(f"columns measured        : {sum(1 for m in measured.values() if m.get('status') == 'MEASURED')}")
    out(f"columns UNMEASURED      : {sum(1 for m in measured.values() if m.get('status') != 'MEASURED')}")
    out(f"NEVER-SUM columns       : {len(never)}")
    out("")
    for m in never:
        out("  * " + summability_warning(m["dataset"], m["column"], measured))
    if apply_it:
        JSON_OUT.write_text(json.dumps(
            {"built_by": "code/1161_money_column_summability.py", "built_date": TODAY,
             "constant_threshold": CONSTANT_THRESHOLD,
             "autocorrelation_max": AUTOCORRELATION_MAX,
             "near_constant_drift": NEAR_CONSTANT_DRIFT,
             "group_key_coverage_floor": KEY_COVERAGE_FLOOR,
             "columns": measured}, indent=2, sort_keys=True), encoding="utf-8")
        out(f"\nwrote {JSON_OUT.relative_to(CEDAR)}")
        write_block(render_block(measured))
        out(f"wrote the marked block into {RULES_MD.relative_to(CEDAR)}")
    return measured


def cmd_verify():
    fails = []
    if not JSON_OUT.exists():
        out("V1 FAIL: docs/MONEY_COLUMN_SUMMABILITY.json is absent")
        return 1
    doc = json.loads(JSON_OUT.read_text(encoding="utf-8"))
    cols = doc.get("columns", {})

    present = 0
    for fname, col, _, _ in SPEC:
        if not (DIST / fname).exists():
            continue
        with (DIST / fname).open(encoding="utf-8-sig", errors="replace", newline="") as fh:
            header = next(csv.reader(fh))
        if col not in header:
            continue
        present += 1
        if f"{fname}::{col}" not in cols:
            fails.append(f"V1: {fname}::{col} is in the delivered file and not in the JSON")
    out(f"V1 declared columns present in dist/customer: {present}; covered by the JSON: "
        f"{present - sum(1 for f in fails if f.startswith('V1'))}")

    never = [m for m in cols.values()
             if m.get("status") == "MEASURED" and m.get("verdict") in NEVER_SUM]
    out(f"V2 never-sum columns recorded: {len(never)} (floor {MIN_NEVER_SUM})")
    if len(never) < MIN_NEVER_SUM:
        fails.append(f"V2: only {len(never)} never-sum columns; the known-bad set is "
                     f"at least {MIN_NEVER_SUM}. The measurement found the wrong thing.")

    tav = cols.get("contractors.csv::total_award_value", {})
    ok3 = (tav.get("status") == "MEASURED" and tav.get("verdict") in NEVER_SUM
           and (tav.get("factor_if_summed") or 0) > 2.0)
    out(f"V3 contractors.total_award_value: verdict={tav.get('verdict')} "
        f"factor={tav.get('factor_if_summed')}")
    if not ok3:
        fails.append("V3: contractors.total_award_value is not recorded as a never-sum "
                     "column with a factor above 2.0 - this is the instance the "
                     "customer review named")

    md = RULES_MD.read_text(encoding="utf-8") if RULES_MD.exists() else ""
    if BEGIN not in md or END not in md:
        fails.append(f"V4: the marked block {BEGIN} is absent from "
                     f"{RULES_MD.relative_to(CEDAR)}")
    elif tav.get("factor_if_summed"):
        want = f"{tav['factor_if_summed']:,.2f}x"
        block = md[md.index(BEGIN):md.rindex(END)]
        if want not in block:
            fails.append(f"V4: the block does not state {want} for "
                         f"contractors.total_award_value; the document and the JSON "
                         f"disagree")
    out(f"V4 marked block present and agreeing with the JSON: "
        f"{'no' if any(f.startswith('V4') for f in fails) else 'yes'}")

    out("")
    if fails:
        for f in fails:
            out("FAIL  " + f)
        return 1
    out("PASS  all four invariants")
    return 0


def cmd_fixtures():
    """Prove each invariant FIRES. Inject, assert exit 1 AND the named line,
    restore, assert exit 0. A check that has never failed on purpose is not
    known to work."""
    import contextlib
    import io

    if not JSON_OUT.exists():
        out("fixtures: run `apply` first - there is nothing to corrupt")
        return 1
    original = JSON_OUT.read_text(encoding="utf-8")
    original_md = RULES_MD.read_text(encoding="utf-8")
    doc = json.loads(original)

    def run():
        buf = io.StringIO()
        with contextlib.redirect_stdout(buf):
            rc = cmd_verify()
        return rc, buf.getvalue()

    results = []
    try:
        rc, txt = run()
        results.append(("baseline PASS", rc == 0, f"exit {rc}"))

        # V1 + V3: drop the named column entirely
        d = json.loads(original)
        d["columns"].pop("contractors.csv::total_award_value", None)
        JSON_OUT.write_text(json.dumps(d), encoding="utf-8")
        rc, txt = run()
        results.append(("V1 fires when a delivered column is missing from the JSON",
                        rc == 1 and "V1:" in txt, f"exit {rc}"))
        results.append(("V3 fires when total_award_value is absent",
                        rc == 1 and "V3:" in txt, f"exit {rc}"))

        # V2: strip every never-sum verdict
        d = json.loads(original)
        for m in d["columns"].values():
            if m.get("verdict") in NEVER_SUM:
                m["verdict"] = "TRANSACTION_ADDITIVE"
        JSON_OUT.write_text(json.dumps(d), encoding="utf-8")
        rc, txt = run()
        results.append(("V2 fires when no never-sum column is recorded",
                        rc == 1 and "V2:" in txt, f"exit {rc}"))

        # V4: move the factor in the JSON so the document disagrees
        d = json.loads(original)
        d["columns"]["contractors.csv::total_award_value"]["factor_if_summed"] = 99.99
        JSON_OUT.write_text(json.dumps(d), encoding="utf-8")
        rc, txt = run()
        results.append(("V4 fires when the document and the JSON disagree",
                        rc == 1 and "V4:" in txt, f"exit {rc}"))

        # V4 again: remove the block from the document
        JSON_OUT.write_text(original, encoding="utf-8")
        a = original_md.index(BEGIN)
        b = original_md.rindex(END) + len(END)
        RULES_MD.write_text(original_md[:a] + original_md[b:], encoding="utf-8",
                            newline="\n")
        rc, txt = run()
        results.append(("V4 fires when the marked block is absent",
                        rc == 1 and "V4:" in txt, f"exit {rc}"))
    finally:
        JSON_OUT.write_text(original, encoding="utf-8")
        RULES_MD.write_text(original_md, encoding="utf-8", newline="\n")

    rc, _ = run()
    results.append(("restored, PASS again", rc == 0, f"exit {rc}"))

    out("1161 fixtures - each invariant must FIRE on an injected violation")
    out("=" * 78)
    bad = 0
    for name, ok, detail in results:
        out(f"  [{'ok ' if ok else 'FAIL'}] {name}  ({detail})")
        bad += 0 if ok else 1
    out("")
    out("all fixtures fired" if not bad else f"{bad} fixture(s) did not fire")
    return 0 if not bad else 1


def main():
    cmd = sys.argv[1] if len(sys.argv) > 1 else "report"
    if cmd == "report":
        cmd_report(False)
        return 0
    if cmd == "fixtures":
        return cmd_fixtures()
    if cmd == "apply":
        cmd_report(True)
        return 0
    if cmd == "verify":
        return cmd_verify()
    out(__doc__)
    return 2


if __name__ == "__main__":
    sys.exit(main())
