#!/usr/bin/env python3
"""
Cedar Press - 415: audit the identity layer. READ-ONLY. Measures, never writes
to data/clean or data/spine.

THE FILE THIS BUILD TREATS AS THE TRUTH
---------------------------------------
    data/spine/cedar_entity_spine.csv   the entity universe and its ids
    data/clean/cedar_identifier_ledger_final.csv   external identifiers
    data/clean/entity_aliases.csv       the name layer
Everything else read here is read to be COMPARED against those three.

WHY
---
The owner asked for a canonical identity layer:

    "We need to create our own ID system so that we can more easily link say
     individuals or other orgs - like our ID system supersedes CICD, and UEI
     etc, but is aligned with one Native entity or org."

Design and reasoning: `docs/CEDAR_ID_SYSTEM.md`. This script is where every
number in that document comes from, so the document can be re-derived instead
of trusted. `AGENTS.md` records what a transcribed number costs: five rows of
the START_HERE dataset table were wrong under a heading claiming verification.

WHAT IT MEASURES
----------------
 1. the two spine id columns - are they the same concept? (they are NOT)
 2. id uniqueness, and whether any id is reused
 3. prefix -> entity_class, with the exceptions named
 4. the parent/ultimate-parent columns and how much of them is self-reference
 5. the external identifier surface: cardinality both ways, tier and method
 6. one-identifier-many-entities defects, by family
 7. the alias layer: coverage, types, and which columns are entirely blank
 8. the assistance table's two id schemes
 9. the value scan: does the legacy short code appear anywhere else at all?

Writes ONLY:
    docs/cedar_id_system_audit.json
    review/identity_layer_audit_<date>.md

    py -3 code/415_audit_identity_layer.py
"""

import csv
import json
import re
import sys
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import cedar_ids as IDS                                     # noqa: E402

CEDAR = Path(__file__).resolve().parent.parent
SPINE_F = CEDAR / "data" / "spine" / "cedar_entity_spine.csv"
LEDGER_F = CEDAR / "data" / "clean" / "cedar_identifier_ledger_final.csv"
ALIAS_F = CEDAR / "data" / "clean" / "entity_aliases.csv"
FUNDING_F = CEDAR / "data" / "clean" / "federal_funding_transactions.csv"
DEFECTS_F = (CEDAR / "review"
             / "identifier_one_to_many_defects_2026-08-26.csv")
FR_ROSTER_F = CEDAR / "data" / "clean" / "federal_recognition_roster.csv"
OUT_JSON = CEDAR / "docs" / "cedar_id_system_audit.json"
TODAY = date.today().isoformat()
OUT_MD = CEDAR / "review" / f"identity_layer_audit_{TODAY}.md"

csv.field_size_limit(min(sys.maxsize, 2**31 - 1))

#: The legacy short code in the spine's `cedar_entity_id` column.
#: Anchored on both ends so it cannot match inside a longer token.
LEGACY_SHORTCODE_RE = re.compile(r"^[TANIE](?:P)?-\d{3,5}$")


def read(path, limit=None):
    if not Path(path).exists():
        return [], []
    with open(path, encoding="utf-8-sig", errors="replace", newline="") as fh:
        rd = csv.DictReader(fh)
        cols = list(rd.fieldnames or [])
        out = []
        for i, r in enumerate(rd):
            if limit and i >= limit:
                break
            out.append(r)
    return out, cols


def g(row, col):
    return (row.get(col) or "").strip()


def section(lines, title):
    lines.append("")
    lines.append(f"## {title}")
    lines.append("")


def main():
    A = {"built_date": TODAY, "built_by": "code/415_audit_identity_layer.py"}
    md = [f"# Identity layer audit - {TODAY}",
          "",
          "Generated by `code/415_audit_identity_layer.py`. Every number in "
          "`docs/CEDAR_ID_SYSTEM.md` is re-derived here rather than "
          "transcribed.", ""]

    # ---------------------------------------------------------------- 1, 2, 3
    spine, spine_cols = read(SPINE_F)
    tid = [g(r, "tribe_id") for r in spine]
    ceid = [g(r, "cedar_entity_id") for r in spine]

    dup_tid = {k: v for k, v in Counter(x for x in tid if x).items() if v > 1}
    dup_ceid = {k: v for k, v in Counter(x for x in ceid if x).items() if v > 1}

    two_columns = {
        "rows": len(spine),
        "columns": len(spine_cols),
        "tribe_id_blank": sum(1 for x in tid if not x),
        "tribe_id_distinct": len({x for x in tid if x}),
        "tribe_id_duplicates": dup_tid,
        "cedar_entity_id_blank": sum(1 for x in ceid if not x),
        "cedar_entity_id_distinct": len({x for x in ceid if x}),
        "cedar_entity_id_duplicates": dup_ceid,
        "rows_where_the_two_are_EQUAL": sum(
            1 for a, b in zip(tid, ceid) if a and b and a == b),
        "rows_where_the_two_DIFFER": sum(
            1 for a, b in zip(tid, ceid) if a and b and a != b),
        "cedar_entity_id_matching_legacy_shortcode_shape": sum(
            1 for x in ceid if LEGACY_SHORTCODE_RE.match(x)),
        "cedar_entity_id_that_is_a_canonical_cedar_id": sum(
            1 for x in ceid if IDS.is_canonical_entity_id(x)),
        "example_pairs": [{"tribe_id": a, "cedar_entity_id": b}
                          for a, b in list(zip(tid, ceid))[:5] if a and b],
        "verdict": "",
    }
    two_columns["verdict"] = (
        "NOT TWO IDS FOR ONE CONCEPT. They are two DIFFERENT concepts sharing "
        "a misleading column name: `tribe_id` is the canonical Cedar id, and "
        "`cedar_entity_id` holds the upstream entity_master.csv register's "
        "`Entity_ID`. They are equal on "
        f"{two_columns['rows_where_the_two_are_EQUAL']} rows and differ on "
        f"{two_columns['rows_where_the_two_DIFFER']}.")
    A["the_two_spine_id_columns"] = two_columns

    # prefix -> class
    pc = defaultdict(Counter)
    for r in spine:
        p = IDS._prefix_of(g(r, "tribe_id")) or "?"
        pc[p][g(r, "entity_class")] += 1
    A["prefix_to_entity_class"] = {
        p: dict(c.most_common()) for p, c in sorted(pc.items())}
    A["prefixes_carrying_more_than_one_class"] = {
        p: dict(c.most_common()) for p, c in pc.items() if len(c) > 1}
    # does the declared hint agree with the file?
    drift = []
    for p, c in pc.items():
        declared = IDS.PREFIX_CLASS_OBSERVED.get(p)
        if declared is None:
            drift.append({"prefix": p, "issue": "not in PREFIX_CLASS_OBSERVED"})
        elif dict(c) != declared:
            drift.append({"prefix": p, "declared": declared,
                          "measured": dict(c)})
    A["prefix_hint_drift_vs_cedar_ids"] = drift

    # class -> is a prefix declared for it?
    classes = Counter(g(r, "entity_class") for r in spine)
    A["entity_class_counts"] = dict(classes.most_common())
    A["entity_classes_with_no_declared_prefix"] = sorted(
        k for k in classes if IDS.class_prefix(k) is None)

    # blank cedar_entity_id by class
    A["legacy_register_id_coverage_by_class"] = {
        k: {"total": v,
            "with_register_id": sum(
                1 for r in spine
                if g(r, "entity_class") == k and g(r, "cedar_entity_id"))}
        for k, v in classes.most_common()}

    # ------------------------------------------------------------------- 4
    ids_set = {x for x in tid if x}
    hier = {}
    for col in ("parent_entity_id", "ultimate_parent_entity_id",
                "ancsa_region_entity_id", "parent_native_entity"):
        vals = [g(r, col) for r in spine]
        nz = [v for v in vals if v]
        selfref = sum(1 for r in spine
                      if g(r, col) and g(r, col) == g(r, "tribe_id"))
        hier[col] = {
            "nonblank": len(nz),
            "distinct": len(set(nz)),
            "self_referential": selfref,
            "values_not_a_spine_id": len({v for v in nz if v not in ids_set}),
            "sample_not_a_spine_id": sorted({v for v in nz
                                             if v not in ids_set})[:8],
        }
    A["hierarchy_columns"] = hier

    # constituent bands: does the id encode the umbrella, and does it resolve?
    bands = []
    for r in spine:
        t = g(r, "tribe_id")
        u = IDS.umbrella_id_for_band(t)
        if u:
            bands.append({"band_id": t, "band_name": g(r, "canonical_name"),
                          "derived_umbrella_id": u,
                          "umbrella_in_spine": u in ids_set,
                          "declared_parent": g(r, "parent_entity_id")})
    A["constituent_bands"] = {
        "n": len(bands),
        "umbrella_derivable_from_the_id_alone": sum(
            1 for b in bands if b["umbrella_in_spine"]),
        "derived_umbrella_agrees_with_declared_parent": sum(
            1 for b in bands
            if b["declared_parent"] and
            b["derived_umbrella_id"] == b["declared_parent"]),
        "rows": bands,
    }

    # ------------------------------------------------------------------- 5, 6
    ledger, ledger_cols = read(LEDGER_F)
    by_type = Counter(g(r, "identifier_type") for r in ledger)
    ent_per_ident = defaultdict(set)
    ident_per_ent = defaultdict(set)
    for r in ledger:
        it, iv, e = (g(r, "identifier_type"), g(r, "identifier"),
                     g(r, "tribe_id"))
        if it and iv:
            if e:
                ent_per_ident[(it, iv)].add(e)
                ident_per_ent[e].add((it, iv))
    many = {k: sorted(v) for k, v in ent_per_ident.items() if len(v) > 1}
    top_holders = sorted(((len(v), k) for k, v in ident_per_ent.items()),
                         reverse=True)[:12]
    A["external_identifiers"] = {
        "ledger_rows": len(ledger),
        "by_type": dict(by_type.most_common()),
        "by_tier": dict(Counter(g(r, "confidence_tier")
                                for r in ledger).most_common()),
        "by_method": dict(Counter(g(r, "attribution_method")
                                  for r in ledger).most_common()),
        "entity_class_blank_rows": sum(
            1 for r in ledger if not g(r, "entity_class")),
        "entity_class_values": dict(Counter(g(r, "entity_class")
                                            for r in ledger).most_common()),
        "rows_with_no_entity": sum(1 for r in ledger if not g(r, "tribe_id")),
        "distinct_identifiers_keyed": len(ent_per_ident),
        "identifiers_resolving_to_MANY_entities_DEFECT": len(many),
        "entities_holding_MANY_identifiers_EXPECTED": sum(
            1 for v in ident_per_ent.values() if len(v) > 1),
        "top_identifier_holders": [{"entity": k, "n_identifiers": n}
                                   for n, k in top_holders],
        "sample_one_identifier_many_entities": [
            {"identifier_type": k[0], "identifier": k[1], "entities": v}
            for k, v in list(many.items())[:10]],
    }

    defects, _ = read(DEFECTS_F)
    fam = Counter(g(r, "defect_family") for r in defects)
    cb_usd = 0.0
    for r in defects:
        if g(r, "defect_family") == "CONSTITUENT_BAND_VS_UMBRELLA_TRIBE":
            try:
                cb_usd += float(g(r, "usd_observed") or 0)
            except ValueError:
                pass
    A["one_to_many_defect_register"] = {
        "file": str(DEFECTS_F.relative_to(CEDAR)),
        "rows": len(defects),
        "by_family": dict(fam.most_common()),
        "constituent_band_usd_observed": round(cb_usd, 2),
    }

    # ------------------------------------------------------------------- 7
    alias, alias_cols = read(ALIAS_F)
    blank_cols = [c for c in alias_cols
                  if not any(g(r, c) for r in alias)]
    alias_entities = {g(r, "entity_id") for r in alias if g(r, "entity_id")}
    A["alias_layer"] = {
        "rows": len(alias),
        "columns": alias_cols,
        "columns_entirely_blank": blank_cols,
        "distinct_entities_covered": len(alias_entities),
        "spine_entities": len(ids_set),
        "spine_entities_with_NO_alias_row": len(ids_set - alias_entities),
        "alias_entities_not_in_the_spine": sorted(
            alias_entities - ids_set)[:10],
        "by_alias_type": dict(Counter(g(r, "alias_type")
                                      for r in alias).most_common()),
        "by_source_system": dict(Counter(g(r, "source_system")
                                         for r in alias).most_common()),
        "by_verification_status": dict(Counter(
            g(r, "verification_status") for r in alias).most_common()),
        "declared_alias_types_unused": sorted(
            set(_domain_alias_types())
            - {g(r, "alias_type") for r in alias}),
        "classes_with_no_alias_coverage": _classes_missing(
            spine, alias_entities),
    }

    # renames available from the FR roster
    fr, _ = read(FR_ROSTER_F)
    renames = [r for r in fr if g(r, "previously_listed_as")]
    keyed = [r for r in renames if g(r, "tribe_id")]
    A["renames_available_from_federal_register"] = {
        "roster_rows": len(fr),
        "rows_carrying_previously_listed_as": len(renames),
        "of_those_keyed_to_a_cedar_entity": len(keyed),
        "distinct_entities": len({g(r, "tribe_id") for r in keyed}),
        "distinct_former_names": len({g(r, "previously_listed_as")
                                      for r in renames}),
        "sample": [{"tribe_id": g(r, "tribe_id"),
                    "current": g(r, "entity_name"),
                    "previously": g(r, "previously_listed_as"),
                    "fr_citation": g(r, "fr_citation")}
                   for r in keyed[:6]],
    }

    # ------------------------------------------------------------------- 8
    if FUNDING_F.exists():
        schemes = Counter()
        n = 0
        with open(FUNDING_F, encoding="utf-8-sig", errors="replace",
                  newline="") as fh:
            for r in csv.DictReader(fh):
                n += 1
                schemes[g(r, "tribe_id_scheme_resolved") or "(column absent)"] += 1
        A["assistance_id_schemes"] = {
            "rows": n,
            "tribe_id_scheme_resolved": dict(schemes.most_common()),
            "note": "The crosswalk is NOT applied. 152 and 24 decline in "
                    "writing: 'the NEID crosswalk is a ruling, not a "
                    "computation.' 122 of 344 candidates rest on the "
                    "containment matcher AGENTS.md forbids from keying a "
                    "dollar. Honoured here.",
        }

    # ------------------------------------------------------------------- 9
    # Does the legacy short code appear ANYWHERE outside the spine column?
    # A cell-by-cell scan, because 327 proved a header scan is not enough.
    legacy_vals = {x for x in ceid if LEGACY_SHORTCODE_RE.match(x)}
    hits = []
    scanned = 0
    for p in sorted(list((CEDAR / "data" / "clean").glob("*.csv"))
                    + list((CEDAR / "data" / "spine").glob("*.csv"))):
        if p.name.endswith(".bak") or ".bak_" in p.name:
            continue
        if p.stat().st_size > 120_000_000:
            hits.append({"file": p.name, "status": "SKIPPED_TOO_LARGE"})
            continue
        scanned += 1
        try:
            with open(p, encoding="utf-8-sig", errors="replace",
                      newline="") as fh:
                rd = csv.DictReader(fh)
                cols = rd.fieldnames or []
                found = Counter()
                for r in rd:
                    for c in cols:
                        v = (r.get(c) or "").strip()
                        if v and v in legacy_vals:
                            found[c] += 1
                for c, k in found.items():
                    hits.append({"file": p.name, "column": c, "cells": k})
        except Exception as e:                       # noqa: BLE001
            hits.append({"file": p.name, "status": f"UNREADABLE: {e}"})
    A["legacy_shortcode_value_scan"] = {
        "distinct_legacy_values": len(legacy_vals),
        "files_scanned": scanned,
        "locations": hits,
        "note": "A rename of the spine column is only safe where this list "
                "is fully enumerated. 327 aborts a whole key migration on ONE "
                "undeclared location, and that discipline is inherited here.",
    }

    # ------------------------------------------------------------------ write
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    tmp = OUT_JSON.with_suffix(".json.part")
    tmp.write_text(json.dumps(A, indent=1, sort_keys=True, default=str),
                   encoding="utf-8")
    tmp.replace(OUT_JSON)

    # markdown
    section(md, "1. The two spine id columns are NOT two ids for one concept")
    for k, v in two_columns.items():
        if k in ("example_pairs", "verdict"):
            continue
        md.append(f"- `{k}` = **{v}**")
    md.append("")
    md.append(f"**Verdict.** {two_columns['verdict']}")
    md.append("")
    md.append("| tribe_id | cedar_entity_id |")
    md.append("|---|---|")
    for e in two_columns["example_pairs"]:
        md.append(f"| `{e['tribe_id']}` | `{e['cedar_entity_id']}` |")

    section(md, "2. Prefix -> entity_class, with the exceptions")
    md.append("| prefix | classes carried |")
    md.append("|---|---|")
    for p, c in A["prefix_to_entity_class"].items():
        md.append(f"| `{p}` | " + " · ".join(
            f"{k} {v}" for k, v in c.items()) + " |")
    md.append("")
    md.append("Prefixes carrying MORE THAN ONE class: "
              + (", ".join(f"`{p}`"
                           for p in A["prefixes_carrying_more_than_one_class"])
                 or "none"))
    md.append(f"Declared-hint drift vs `cedar_ids.PREFIX_CLASS_OBSERVED`: "
              f"{len(drift)}")

    section(md, "3. Hierarchy columns")
    md.append("| column | nonblank | distinct | self-referential | "
              "not a spine id |")
    md.append("|---|---:|---:|---:|---:|")
    for c, v in hier.items():
        md.append(f"| `{c}` | {v['nonblank']} | {v['distinct']} | "
                  f"{v['self_referential']} | {v['values_not_a_spine_id']} |")

    section(md, "4. Constituent bands - does the ID carry the umbrella?")
    cbb = A["constituent_bands"]
    md.append(f"- band ids (`CNSF-`/`CNSS-`): **{cbb['n']}**")
    md.append(f"- umbrella derivable from the id ALONE and present in the "
              f"spine: **{cbb['umbrella_derivable_from_the_id_alone']}**")
    md.append(f"- derived umbrella agrees with the declared "
              f"`parent_entity_id`: **"
              f"{cbb['derived_umbrella_agrees_with_declared_parent']}**")
    md.append(f"- `CONSTITUENT_BAND_VS_UMBRELLA_TRIBE` defects: "
              f"**{A['one_to_many_defect_register']['by_family'].get('CONSTITUENT_BAND_VS_UMBRELLA_TRIBE', 0)}**"
              f" on ${A['one_to_many_defect_register']['constituent_band_usd_observed']:,.2f}"
              " observed")

    section(md, "5. External identifiers")
    e = A["external_identifiers"]
    md.append(f"- ledger rows **{e['ledger_rows']:,}** · "
              + " · ".join(f"{k} {v:,}" for k, v in e["by_type"].items()))
    md.append(f"- `entity_class` BLANK on **{e['entity_class_blank_rows']:,}** "
              f"rows ({100*e['entity_class_blank_rows']/max(1,e['ledger_rows']):.0f}%)")
    md.append(f"- one identifier -> MANY entities (**a defect**): "
              f"**{e['identifiers_resolving_to_MANY_entities_DEFECT']}**")
    md.append(f"- one entity -> MANY identifiers (**expected**): "
              f"**{e['entities_holding_MANY_identifiers_EXPECTED']}**")
    md.append("")
    md.append("Top identifier holders (many-per-entity is normal - the 8(a) "
              "nine-year term mints successors, and a large ANC family is one "
              "entity with dozens of registrations):")
    md.append("")
    for h in e["top_identifier_holders"]:
        md.append(f"- `{h['entity']}` — {h['n_identifiers']}")

    section(md, "6. Alias layer")
    a = A["alias_layer"]
    md.append(f"- rows **{a['rows']:,}**, covering **"
              f"{a['distinct_entities_covered']:,}** of "
              f"**{a['spine_entities']:,}** spine entities")
    md.append(f"- **{a['spine_entities_with_NO_alias_row']}** spine entities "
              f"have NO alias row at all")
    md.append(f"- columns entirely blank: "
              + (", ".join(f"`{c}`" for c in a["columns_entirely_blank"])
                 or "none"))
    md.append(f"- declared `cedar_domain.ALIAS_TYPES` never used: "
              + (", ".join(f"`{t}`" for t in a["declared_alias_types_unused"])
                 or "none"))
    md.append("")
    for k, v in a["by_alias_type"].items():
        md.append(f"  - `{k}` {v:,}")

    section(md, "7. Renames available from the Federal Register")
    rn = A["renames_available_from_federal_register"]
    for k in ("roster_rows", "rows_carrying_previously_listed_as",
              "of_those_keyed_to_a_cedar_entity", "distinct_entities",
              "distinct_former_names"):
        md.append(f"- `{k}` = **{rn[k]:,}**")

    section(md, "8. Legacy short-code value scan")
    ls = A["legacy_shortcode_value_scan"]
    md.append(f"- distinct legacy values: **{ls['distinct_legacy_values']}**")
    md.append(f"- files scanned: **{ls['files_scanned']}**")
    md.append("- locations found:")
    for h in ls["locations"]:
        md.append(f"  - `{h.get('file')}` "
                  f"{h.get('column', h.get('status', ''))} "
                  f"{h.get('cells', '')}")

    OUT_MD.parent.mkdir(parents=True, exist_ok=True)
    tmp2 = OUT_MD.with_suffix(".md.part")
    tmp2.write_text("\n".join(md) + "\n", encoding="utf-8")
    tmp2.replace(OUT_MD)

    # concurrency rule 4: verify by RE-READING, never by trusting the run log
    back = json.loads(OUT_JSON.read_text(encoding="utf-8"))
    assert back["the_two_spine_id_columns"]["rows"] == len(spine)
    print(f"wrote {OUT_JSON.relative_to(CEDAR)} "
          f"({OUT_JSON.stat().st_size:,} bytes, re-read OK)")
    print(f"wrote {OUT_MD.relative_to(CEDAR)} "
          f"({OUT_MD.stat().st_size:,} bytes)")
    print()
    print("HEADLINES")
    print(f"  spine rows                         {len(spine):,}")
    print(f"  tribe_id / cedar_entity_id EQUAL   "
          f"{two_columns['rows_where_the_two_are_EQUAL']}")
    print(f"  cedar_entity_id blank              "
          f"{two_columns['cedar_entity_id_blank']}")
    print(f"  ...that is a canonical Cedar id    "
          f"{two_columns['cedar_entity_id_that_is_a_canonical_cedar_id']}")
    print(f"  prefixes with >1 class             "
          f"{len(A['prefixes_carrying_more_than_one_class'])}")
    print(f"  one-identifier-many-entities       "
          f"{e['identifiers_resolving_to_MANY_entities_DEFECT']}")
    print(f"  spine entities with no alias row   "
          f"{a['spine_entities_with_NO_alias_row']}")
    print(f"  legacy shortcode locations         "
          f"{len(ls['locations'])}")


def _domain_alias_types():
    try:
        import cedar_domain as D
        return D.ALIAS_TYPES
    except Exception:                                        # noqa: BLE001
        return frozenset()


def _classes_missing(spine, covered):
    out = Counter()
    for r in spine:
        if g(r, "tribe_id") not in covered:
            out[g(r, "entity_class")] += 1
    return dict(out.most_common())


if __name__ == "__main__":
    main()
