#!/usr/bin/env python3
r"""
Cedar Press - 78: Content analysis of the four text corpora.

WHY THIS EXISTS
---------------
Elijah, 2026-08-06: "we also should probably do content analysis on some of
these too"

Cedar Press holds four large text corpora that are currently used only as row
counts. A row count is inventory, not a finding. This script turns three of
them into measured, per-year series, and it reports how wrong each classifier
is rather than hoping nobody asks.

THE RULE THIS SCRIPT IS BUILT AROUND
------------------------------------
**A classification is evidence, so it ships with an error rate.** A theme count
with no audited accuracy is not a finding; it is a regex with a press release.
Every classifier here has a hand-coded sample, and the confusion cases are
published in full (`content_audit_*.csv`) so a reader can overrule us.

Standing rule 10 applies with force: every number in docs/CONTENT_ANALYSIS.md is
regenerated by this script. Do not hand-edit them.

WHAT IT DOES NOT DO
-------------------
- It does not attribute any document to an entity. A concurrent agent owns
  entity keys; this script only reads `tribe_id` where it already exists, and
  writes it nowhere.
- It does not use, trust, or republish `action_type_rule` or
  `keyword_terms_matched` from federal_actions.csv. Those are INTERNAL: their
  values disclose the recipe, and a recipe cannot be its own ground truth.
- It does not modify data/spine/, data/clean/cedar_*, federal_actions.csv, or
  review/cedar_*.html.

USAGE
    py -3 code/78_content_analysis.py --emit-audit   # draw hand-coding samples
    py -3 code/78_content_analysis.py               # build series + accuracy

The audit files are drawn with a FROZEN seed and the classifiers are frozen
before drawing. Errors found in the audit are REPORTED, not patched - patching
a classifier against its own audit sample turns a measurement into a claim.
"""

import csv
import html
import json
import random
import re
import sys
from collections import Counter, defaultdict
from datetime import date
from pathlib import Path

csv.field_size_limit(10 ** 8)

CEDAR = Path(__file__).resolve().parent.parent
CLEAN = CEDAR / "data" / "clean"
TODAY = date.today().isoformat()

LOBBY = CLEAN / "native_entity_lobbying_disclosures.csv"
FR = CLEAN / "federal_actions.csv"
BILLS = CLEAN / "native_bills.csv"

AUDIT_SEED = 20260806          # frozen. do not change without redrawing all.
N_AUDIT_LOBBY = 120
N_AUDIT_FR_TIER = 120
N_AUDIT_FR_THEME = 110


def read_csv(p):
    p = Path(p)
    if not p.exists():
        return []
    with open(p, encoding="utf-8-sig", errors="replace", newline="") as fh:
        return list(csv.DictReader(fh))


def write_csv(p, rows, cols=None):
    p = Path(p)
    if not rows:
        print(f"  (skipped {p.name}: no rows)")
        return
    # Union the keys across ALL rows, first-seen order - not just rows[0].
    #
    # Taking columns from the first row silently dropped
    # `estimated_true_tribal_subject_documents` from content_analysis_accuracy.csv,
    # because the first row was a classifier that has no such field and
    # extrasaction="ignore" then discarded it everywhere. The doc cited a number
    # the CSV did not contain, which is exactly the failure standing rule 10
    # exists to prevent.
    if cols is None:
        cols, seen = [], set()
        for r in rows:
            for k in r:
                if k not in seen:
                    seen.add(k)
                    cols.append(k)
    with open(p, "w", encoding="utf-8", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=cols, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)
    print(f"  wrote {p.name:52s} {len(rows):>7,} rows")


# =====================================================================
# 1. LOBBYING - what Indian Country lobbies ABOUT
# =====================================================================
#
# The LDA gives filers a 79-code issue taxonomy. For this population it is
# nearly useless: 18,403 of 22,699 coded filings carry "IND" (Indian /
# Native American affairs). The federal disclosure system collapses everything
# a tribe does into a single code, which is precisely why the free-text
# `specific_issues_text` has to be read.
#
# Unit of classification is the SEGMENT, not the filing. Filers write one issue
# per line, and repeat the whole block across activity records separated by
# "|||". Classifying the concatenated blob would score a filing as "energy"
# because one of nine lines mentioned a pipeline, and would count the same line
# up to nine times. So: split, dedupe, classify each segment, roll up.

LOBBY_FAMILIES = [
    ("gaming",
     r"\bgaming\b|\bgamble|\bcasino|\bIGRA\b|class (ii|iii)\b|"
     r"indian gaming regulatory|slot machine|sports bett|internet gam|"
     r"off-?reservation gam|compact.{0,25}gaming|gaming.{0,25}compact"),
    ("health",
     r"\bhealth\b|\bIHS\b|indian health|medicaid|medicare|\bdiabetes\b|"
     r"behavioral health|substance abuse|opioid|contract health|\bCHEF\b|"
     r"\bhospital|clinic\b|mental health|\bCOVID|\bpandemic|coronavirus|\bvaccin"),
    ("education",
     r"\beducation\b|\bschool|\bBIE\b|bureau of indian education|"
     r"tribal college|\bTCU\b|impact aid|head start|johnson[- ]o.?malley|"
     r"\bJOM\b|student|scholarship"),
    ("land_water",
     r"land[- ]into[- ]trust|fee[- ]to[- ]trust|\btrust land|land acquisition|"
     r"land claim|\ballotment|\bprobate\b|fractionat|land consolidat|"
     r"\bwater right|water settlement|\birrigation\b|\bwater\b|"
     r"reservation boundar|land use|land issues|sacred site|"
     r"\brights?[- ]of[- ]way\b|land purchase|\bright of way"),
    ("energy",
     r"\benergy\b|\boil\b|\bgas\b|\bcoal\b|\bpipeline|\bhydro|\bsolar\b|"
     r"\bwind (power|energy|farm)|renewable|\bFERC\b|"
     r"electric (util|transm|reliab|generat)|power (plant|generation)|"
     r"transmission line|\bdrilling|\bmineral|\bmining\b|geothermal|biomass|"
     r"\bLNG\b|distributed generation|generating station|"
     r"power marketing administration|\bmine\b|\bmines\b|\butilit(y|ies)\b"),
    ("taxation",
     r"\btax\b|\btaxes\b|\btaxation|tax[- ]exempt|\bbond(s|ing)?\b|excise|"
     r"internal revenue|\bIRS\b|general welfare exclusion|new markets tax|"
     r"\bNMTC\b|tax credit|severance tax"),
    ("public_safety",
     r"law enforcement|public safety|\bpolice\b|\bcrime\b|criminal justice|"
     r"\bVAWA\b|violence against women|\btribal court|\bjustice\b|"
     r"\bdetention\b|\bjail\b|\bpolicing|missing and murdered|\bMMIW\b|"
     r"domestic violence|sex offender|\bICWA\b|indian child welfare|child protect"),
    ("broadband",
     r"broadband|\btelecom|\binternet\b(?!.{0,15}gam)|spectrum\b|\bFCC\b|"
     r"universal service|\bE-?rate\b|connectivity|wireless|\bdigital divide|"
     r"\bcable\b"),
    ("transportation",
     r"\btransportation\b|\bhighway|\broad(s|way)?\b|\bbridge|\btransit\b|"
     r"\bBIA road|\bIRR\b|indian reservation roads|\bFAST Act\b|"
     r"surface transportation|\bairport|\baviation\b|\bferry\b|\brailroad|\bport\b"),
    ("appropriations",
     r"\bappropriat|\bapprops?\b|\bbudget|continuing resolution|\bomnibus\b|"
     r"fiscal year|\bFY ?\d{2,4}|sequestration|\bearmark|\bstimulus\b|"
     r"CARES Act|American Rescue Plan|Inflation Reduction Act|"
     r"Infrastructure Investment and Jobs|\bIIJA\b|\bARPA\b|debt (ceiling|limit)"),
    ("housing",
     r"\bhousing\b|\bNAHASDA\b|\bIHBG\b|\bHUD\b|homeless|home ?ownership|"
     r"\bmortgage|\bsection 184\b"),
    ("econ_dev_contracting",
     r"economic development|\b8\(?a\)?\b|small business|\bSBA\b|"
     r"government contracting|federal contracting|procurement|set[- ]aside|"
     r"\bHUBZone|\bbuy indian\b|job creation|workforce|\bemployment\b|"
     r"business development|\bcontracting\b"),
    ("sovereignty_governance",
     r"\bsovereign|self[- ]governance|self[- ]determination|"
     r"government[- ]to[- ]government|federal recognition|federal acknowledgment|"
     r"\brestoration\b|tribal government|trust responsibilit|\bconsultation\b|"
     r"contract support cost|\b638\b|\bPL ?93-?638|jurisdiction|\bcarcieri\b|"
     r"tribal labor sovereignt|\btreaty\b|federal indian (policy|legislation|law)|"
     r"tribal[- ]federal relations|bureau of indian affairs|\bBIA\b|"
     r"trust claim|\bBIE\b"),
    ("environment_nr",
     r"\benvironment|\bEPA\b|clean water act|clean air|air quality|"
     r"\bwater quality\b|endangered species|\bESA\b|\bwildlife\b|"
     r"\bfisher(y|ies)\b|\bsalmon\b|\bforest|\bwildfire\b|natural resource|"
     r"\bhunting\b|\bconservation\b|superfund|\bclimate\b|\bNEPA\b"),
    ("culture_repatriation",
     r"\bNAGPRA\b|repatriat|cultural (resource|propert|preservation)|"
     r"historic preservation|\bTHPO\b|sacred|human remains|"
     r"\blanguage (preservation|program)|\bmuseum\b|\bmascot|\bSTOP Act\b|"
     r"objects of patrimony|\bpatrimony\b"),
    ("social_services",
     r"social services|\bwelfare\b|\bTANF\b|child care|\belder|\bnutrition\b|"
     r"food distribution|\bFDPIR\b|\bSNAP\b|\bLIHEAP\b|\bveteran"),
    ("agriculture",
     r"\bagricultur|\bfarm bill\b|\branching|\blivestock|\bUSDA\b|\bgrazing\b"),
]
LOBBY_RX = [(n, re.compile(p, re.I)) for n, p in LOBBY_FAMILIES]

# Segments that say nothing: "general tribal issues", "monitor Indian
# legislation". These are not an unclassified failure, they are a filer
# declining to disclose, and they are counted and published as such.
LOBBY_GENERIC = re.compile(
    r"^(general |monitor|monitoring|various |all )?"
    r"(matters?|issues?|legislation|activit\w+|representation|advocacy)?[ ,]*"
    r"(relat\w+ to |regarding |concerning |affecting |pertaining to |on )?"
    r"(general |various |all )?"
    r"(native american|american indian|indian|tribal|tribe|alaska native)[ a-z]*"
    r"(issues?|matters?|affairs|legislation|policy|interests?|programs?|"
    r"representation|concerns?|relations|government|country|nations?)?[ .]*$",
    re.I)


def lobby_segments(txt):
    """Split a specific_issues_text blob into deduplicated issue lines."""
    txt = html.unescape(html.unescape(txt or ""))
    out = set()
    for blob in txt.split("|||"):
        for line in re.split(r"[\n\r;]+", blob):
            line = re.sub(r"\s+", " ", line).strip(" .,-\u2022*\t")
            if len(line) >= 4:
                out.add(line)
    return sorted(out)


def lobby_classify(seg):
    fams = {n for n, rx in LOBBY_RX if rx.search(seg)}
    if fams:
        return fams, "matched"
    if LOBBY_GENERIC.match(seg):
        return set(), "generic_boilerplate"
    return set(), "unclassified"


def build_lobbying(rows):
    print("\n[1] Lobbying: what Indian Country lobbies about")
    per_filing, seg_status = [], Counter()
    fam_year = defaultdict(Counter)          # family -> year -> filings
    year_total = Counter()
    coded_year = Counter()

    for r in rows:
        yr = (r.get("filing_year") or "").strip()
        if not yr.isdigit():
            continue
        yr = int(yr)
        year_total[yr] += 1
        segs = lobby_segments(r.get("specific_issues_text"))
        fams, statuses = set(), Counter()
        for s in segs:
            f, st = lobby_classify(s)
            fams |= f
            statuses[st] += 1
            seg_status[st] += 1
        if not segs:
            seg_status["no_text_disclosed"] += 1
        per_filing.append({
            "filing_uuid": r.get("filing_uuid", ""),
            "filing_year": yr,
            "client_name": r.get("client_name", ""),
            "entity_id": r.get("entity_id", ""),
            "lda_issue_codes": r.get("lobbying_issues_codes", ""),
            "n_segments": len(segs),
            "n_segments_matched": statuses.get("matched", 0),
            "n_segments_generic": statuses.get("generic_boilerplate", 0),
            "n_segments_unclassified": statuses.get("unclassified", 0),
            "issue_families": "|".join(sorted(fams)),
            "n_issue_families": len(fams),
            "text_status": ("no_text" if not segs else
                            "classified" if fams else
                            "generic_only" if statuses.get("generic_boilerplate")
                            else "unclassified_only"),
            "classifier": "78_content_analysis.py::lobby_classify",
            "classifier_version": TODAY,
        })
        if fams:
            coded_year[yr] += 1
            for f in fams:
                fam_year[f][yr] += 1

    write_csv(CLEAN / "lobbying_issue_families_filing.csv", per_filing)

    # Two denominators, and the difference matters more than it looks.
    #
    # share_of_classified_filings is contaminated: the mean number of issue
    # families disclosed per filing rose from ~2.0 in 2002-03 to ~3.1 by the
    # 2020s. Against that denominator almost every family "rises", which is a
    # fact about filing verbosity, not about what tribes lobby on. Read alone it
    # would have produced a whole page of spurious growth findings.
    #
    # share_of_family_mentions is compositional - each family's share of all
    # family mentions that year - and is neutral to how much a filer wrote.
    # It is the series to quote for change over time.
    mentions_year = Counter()
    for f in fam_year:
        for y, n in fam_year[f].items():
            mentions_year[y] += n

    series = []
    years = sorted(year_total)
    for f in sorted(fam_year):
        for y in years:
            n = fam_year[f][y]
            series.append({
                "issue_family": f, "filing_year": y, "n_filings": n,
                "n_filings_with_any_family": coded_year[y],
                "share_of_classified_filings":
                    round(n / coded_year[y], 4) if coded_year[y] else "",
                "n_family_mentions_that_year": mentions_year[y],
                "share_of_family_mentions":
                    round(n / mentions_year[y], 4) if mentions_year[y] else "",
                "n_filings_total_that_year": year_total[y],
                "preferred_series_for_trend": "share_of_family_mentions",
            })
    write_csv(CLEAN / "lobbying_issue_family_year.csv", series)

    verb = []
    for y in years:
        fl = [r for r in per_filing
              if r["filing_year"] == y and r["text_status"] == "classified"]
        if fl:
            verb.append({
                "filing_year": y, "n_classified_filings": len(fl),
                "mean_issue_families_per_filing":
                    round(sum(r["n_issue_families"] for r in fl) / len(fl), 3),
                "mean_segments_per_filing":
                    round(sum(r["n_segments"] for r in fl) / len(fl), 3),
            })
    write_csv(CLEAN / "lobbying_disclosure_verbosity_year.csv", verb)

    print(f"  segment outcomes: {dict(seg_status)}")
    return per_filing, seg_status, year_total, coded_year, fam_year


# =====================================================================
# 2. FEDERAL REGISTER - what the federal government does, by type
# =====================================================================
#
# The single most important fact about this corpus: it was assembled by
# full-text keyword net (153,143 of 156,452 rows are net_caught="keyword").
# A document enters if the word "tribal" appears anywhere in its body. An EPA
# rule on chromium electroplating that mentions tribal lands once is in the
# corpus on identical footing with a fee-to-trust proclamation.
#
# We hold title, abstract, action and dates - NOT body text. So for a document
# whose Native term is only in the body, we have no text with which to classify
# it and no text with which to verify it belongs. That is a hard limit, and the
# tiering below states it rather than papering over it.

FR_STRONG = re.compile(
    r"\bindian\b|\bindians\b|\btribal\b|\btribes?\b|native american|"
    r"alaska native|native hawaiian|\bNAGPRA\b|\brancheria\b", re.I)
FR_WEAK = re.compile(
    r"\breservation\b|\ballotment\b|\banilca\b|\bancsa\b|\bpueblo\b|"
    r"\bnavajo\b|\bcherokee\b", re.I)

FR_THEMES = [
    ("nagpra_repatriation",
     r"\bNAGPRA\b|repatriat|inventory completion|intent to repatriate|"
     r"human remains|funerary object|sacred object|cultural patrimony|"
     r"native american graves"),
    ("gaming",
     r"\bgaming\b|\bIGRA\b|class III|gaming compact|tribal-state compact|"
     r"indian gaming|\bcasino\b"),
    ("land_into_trust",
     r"land[- ]into[- ]trust|fee[- ]to[- ]trust|trust acquisition|"
     r"reservation proclamation|proclaiming.{0,30}reservation|"
     r"land acquisition.{0,30}trust"),
    ("federal_acknowledgment",
     r"federal acknowledg|federal recognition|petition for acknowledg|"
     r"acknowledgment of.{0,20}tribe|\bpart 83\b|entities recognized|"
     r"indian entities recognized"),
    ("consultation",
     r"\bconsultation\b|tribal consultation|government-to-government|"
     r"\bconsult(ing|s)? with\b.{0,40}trib"),
    ("energy_minerals",
     r"\benergy\b|\boil\b|\bgas\b|\bcoal\b|\bmineral|\bmining\b|\bpipeline|"
     r"\bhydro|\bsolar\b|\bwind\b|geothermal|\bFERC\b"),
    ("health_ihs",
     r"indian health|\bIHS\b|contract health|\bmedicaid\b|\bmedicare\b|"
     r"health service|\bhospital\b|\bclinic\b|community health"),
    ("probate_allotment",
     r"\bprobate\b|\ballotment|\bfractionat|land consolidat|\bheirship\b|"
     r"inherited interest"),
    ("liquor", r"liquor (ordinance|control|law)|alcoholic beverage|\bliquor\b"),
    ("self_governance_638",
     r"self-?governance|self-?determination|\b638\b|Public Law 93-?638|"
     r"contract support cost|annual funding agreement|\bISDEAA\b"),
    ("housing", r"\bhousing\b|\bNAHASDA\b|\bIHBG\b|indian housing"),
    ("roads_transportation",
     r"\broad(s|way)?\b|\bhighway\b|\btransportation\b|\bbridge\b|\btransit\b|"
     r"indian reservation roads|\btribal transportation"),
    ("icwa_child_welfare",
     r"\bICWA\b|indian child welfare|foster care|child protect|\bchild custody\b"),
    ("water_rights",
     r"water right|water settlement|\birrigation\b|\bwater quality\b|"
     r"\bwater supply\b|instream flow"),
    ("epa_treatment_as_state",
     r"treatment as a state|treatment in a similar manner|"
     r"tribal implementation plan"),
    ("education",
     r"\beducation\b|\bschool\b|\bBIE\b|tribal college|impact aid|\bstudent\b"),
    ("environment_nr",
     r"\benvironment|clean water act|clean air act|endangered species|"
     r"\bwildlife\b|\bfisher(y|ies)\b|\bforest|\bNEPA\b|environmental impact"),
    ("grants_funding",
     r"\bgrant\b|\bfunding opportunit|notice of funding|\bNOFO\b|\bNOFA\b|"
     r"award announcement|\bsolicitation\b"),
    ("ancsa_alaska",
     r"\bANCSA\b|alaska native claims|\bANILCA\b|village corporation|"
     r"regional corporation|\bconveyance\b"),
]
FR_RX = [(n, re.compile(p, re.I)) for n, p in FR_THEMES]


def fr_tier(r):
    """Evidence tier for 'is this document ABOUT Indian Country?'

    title_subject     - a Native term is in the TITLE. Strongest available
                        evidence short of reading the body.
    abstract_subject  - Native term in the abstract but not the title.
    weak_term_only    - only an ambiguous term ('reservation', 'Pueblo',
                        which also mean campsite bookings and New Mexico towns).
    body_only         - no Native term in any field we hold. UNVERIFIABLE from
                        this dataset. Not a claim that it is irrelevant - a
                        statement that we cannot see.
    """
    t, a = r.get("title") or "", r.get("abstract") or ""
    if FR_STRONG.search(t):
        return "title_subject"
    if FR_STRONG.search(a):
        return "abstract_subject"
    if FR_WEAK.search(t) or FR_WEAK.search(a):
        return "weak_term_only"
    return "body_only_unverifiable"


def fr_themes(r):
    txt = (r.get("title") or "") + " || " + (r.get("abstract") or "")
    return [n for n, rx in FR_RX if rx.search(txt)]


def build_fr(rows):
    print("\n[2] Federal Register: what the government does, by type")
    tiers = Counter()
    out, theme_year, tier_year = [], defaultdict(Counter), defaultdict(Counter)
    classifiable_year = Counter()
    agency_year = defaultdict(Counter)
    agency_theme = defaultdict(Counter)

    for r in rows:
        t = fr_tier(r)
        tiers[t] += 1
        yr = (r.get("publication_date") or "")[:4]
        yr = int(yr) if yr.isdigit() else None
        if yr:
            tier_year[t][yr] += 1
        classifiable = t in ("title_subject", "abstract_subject")
        th = fr_themes(r) if classifiable else []
        if classifiable and yr:
            classifiable_year[yr] += 1
            for x in th:
                theme_year[x][yr] += 1
        if classifiable:
            for a in (r.get("agency_names") or "").split("|"):
                a = a.strip()
                if a:
                    if yr:
                        agency_year[a][yr] += 1
                    for x in th:
                        agency_theme[a][x] += 1
        out.append({
            "document_number": r.get("document_number", ""),
            "publication_date": r.get("publication_date", ""),
            "publication_year": yr or "",
            "type": r.get("type", ""),
            "title": r.get("title", ""),
            "agency_names": r.get("agency_names", ""),
            "relevance_tier": t,
            "content_classifiable": int(classifiable),
            "themes": "|".join(th),
            "n_themes": len(th),
            "classifier": "78_content_analysis.py::fr_themes",
            "classifier_version": TODAY,
            "html_url": r.get("html_url", ""),
        })

    write_csv(CLEAN / "fr_content_classification.csv", out)

    ser = []
    yrs = sorted({r["publication_year"] for r in out if r["publication_year"]})
    for th in sorted(theme_year):
        for y in yrs:
            n = theme_year[th][y]
            ser.append({
                "theme": th, "publication_year": y, "n_documents": n,
                "n_classifiable_documents_that_year": classifiable_year[y],
                "share_of_classifiable":
                    round(n / classifiable_year[y], 4) if classifiable_year[y] else "",
            })
    write_csv(CLEAN / "fr_theme_year.csv", ser)

    tser = [{"relevance_tier": t, "publication_year": y, "n_documents": tier_year[t][y]}
            for t in sorted(tier_year) for y in yrs if tier_year[t][y]]
    write_csv(CLEAN / "fr_relevance_tier_year.csv", tser)

    print("  relevance tiers: " + ", ".join(
        f"{k}={v:,} ({100*v/len(rows):.1f}%)" for k, v in tiers.most_common()))
    return out, tiers, theme_year, classifiable_year, agency_year, agency_theme


# =====================================================================
# 3. AGENCIES - where policy attention sits vs where advocacy is aimed
# =====================================================================
#
# Two vocabularies that do not agree. FR says "Interior Department; Indian
# Affairs Bureau"; LDA says "Interior, Dept of (DOI)". Both are normalised to a
# coarse department label. The normaliser is deliberately coarse: a fine-grained
# crosswalk would imply a precision neither source supports.

AGENCY_NORM = [
    ("Congress", r"house of representatives|\bsenate\b|\bcongress\b|"
                 r"congressional budget|government accountability"),
    ("Interior", r"\binterior\b|\bDOI\b|indian affairs|fish and wildlife|"
                 r"national park|land management|bureau of reclamation|"
                 r"surface mining|ocean energy|indian education"),
    ("HHS", r"health and human services|health & human services|\bHHS\b|"
            r"medicare|medicaid|indian health|centers for disease|"
            r"food and drug|children and families|substance abuse and mental"),
    ("EPA", r"environmental protection"),
    ("Agriculture", r"\bagriculture\b|\bUSDA\b|forest service|rural (utilities|development|housing)|"
                    r"food and nutrition|natural resources conservation"),
    ("Justice", r"\bjustice\b|\bDOJ\b|drug enforcement|federal bureau of investigation|"
                r"alcohol, tobacco|bureau of prisons"),
    ("Transportation", r"\btransportation\b|federal highway|federal aviation|"
                       r"federal transit|federal railroad|maritime administration"),
    ("Energy", r"\benergy\b|federal energy regulatory|\bFERC\b|"
               r"bonneville power|western area power"),
    ("Defense", r"\bdefense\b|\bDOD\b|army|navy|air force|corps of engineers|\bDLA\b"),
    ("HUD", r"housing and urban|\bHUD\b"),
    ("Education", r"\beducation\b"),
    ("Treasury", r"\btreasury\b|internal revenue|\bIRS\b"),
    ("Commerce", r"\bcommerce\b|oceanic and atmospheric|\bNOAA\b|census bureau|"
                 r"economic development administration|patent and trademark|\bNTIA\b"),
    ("Labor", r"\blabor\b|occupational safety|employment and training"),
    ("Homeland Security", r"homeland security|coast guard|emergency management|\bFEMA\b|"
                          r"customs and border|immigration and customs"),
    ("FCC", r"federal communications"),
    ("SBA", r"small business administration"),
    ("Veterans Affairs", r"veterans affairs"),
    ("State", r"state, dept of|\bstate department\b"),
    ("NRC", r"nuclear regulatory"),
    ("White House / EOP", r"executive office|management & budget|management and budget|"
                          r"\bOMB\b|white house|president"),
]
AGENCY_RX = [(n, re.compile(p, re.I)) for n, p in AGENCY_NORM]


def norm_agency(raw):
    for n, rx in AGENCY_RX:
        if rx.search(raw):
            return n
    return "Other / unmapped"


def build_agencies(fr_rows, lob_rows, agency_year):
    print("\n[3] Agencies: policy attention vs advocacy targeting")

    # FR side - only documents we can verify are tribal-subject.
    fr_dept, fr_dept_year = Counter(), defaultdict(Counter)
    for r in fr_rows:
        if not r["content_classifiable"]:
            continue
        y = r["publication_year"]
        for a in (r["agency_names"] or "").split("|"):
            a = a.strip()
            if not a:
                continue
            d = norm_agency(a)
            fr_dept[d] += 1
            if y:
                fr_dept_year[d][y] += 1

    # Lobbying side - government_entities is filer-reported, not inferred.
    lob_dept, lob_dept_year = Counter(), defaultdict(Counter)
    raw_targets = Counter()
    for r in lob_rows:
        y = (r.get("filing_year") or "").strip()
        y = int(y) if y.isdigit() else None
        seen = set()
        for a in (r.get("government_entities") or "").split("|"):
            a = a.strip()
            if not a:
                continue
            raw_targets[a] += 1
            d = norm_agency(a)
            if d in seen:
                continue
            seen.add(d)
            lob_dept[d] += 1
            if y:
                lob_dept_year[d][y] += 1

    fr_tot = sum(fr_dept.values()) or 1
    lob_tot = sum(lob_dept.values()) or 1
    # Congress publishes nothing in the Federal Register, so a "Congress" gap of
    # +42pp measures the two sources' definitions, not anybody's behaviour. The
    # executive-only shares are the ones that compare like with like.
    EXCL = {"Congress"}
    fr_x = sum(v for k, v in fr_dept.items() if k not in EXCL) or 1
    lob_x = sum(v for k, v in lob_dept.items() if k not in EXCL) or 1
    gap = []
    for d in sorted(set(fr_dept) | set(lob_dept)):
        fs, ls = fr_dept[d] / fr_tot, lob_dept[d] / lob_tot
        gap.append({
            "department": d,
            "fr_documents": fr_dept[d],
            "fr_share_of_agency_mentions": round(fs, 4),
            "lobbying_filings_targeting": lob_dept[d],
            "lobbying_share_of_targets": round(ls, 4),
            "advocacy_minus_attention_pp": round((ls - fs) * 100, 2),
            "fr_share_executive_only":
                "" if d in EXCL else round(fr_dept[d] / fr_x, 4),
            "lobbying_share_executive_only":
                "" if d in EXCL else round(lob_dept[d] / lob_x, 4),
            "gap_pp_executive_only": "" if d in EXCL else round(
                (lob_dept[d] / lob_x - fr_dept[d] / fr_x) * 100, 2),
            "fr_basis": "agency_names on classifiable (title/abstract-subject) FR documents",
            "lobbying_basis": "government_entities as reported by the filer",
        })
    gap.sort(key=lambda r: -abs(r["gap_pp_executive_only"]
                               if r["gap_pp_executive_only"] != "" else 0))
    write_csv(CLEAN / "agency_attention_vs_advocacy.csv", gap)

    ser = []
    yrs = sorted({y for d in fr_dept_year for y in fr_dept_year[d]} |
                 {y for d in lob_dept_year for y in lob_dept_year[d]})
    for d in sorted(set(fr_dept) | set(lob_dept)):
        for y in yrs:
            f, l = fr_dept_year[d].get(y, 0), lob_dept_year[d].get(y, 0)
            if f or l:
                ser.append({"department": d, "year": y,
                            "fr_documents": f, "lobbying_filings_targeting": l})
    write_csv(CLEAN / "agency_attention_vs_advocacy_year.csv", ser)

    write_csv(CLEAN / "lobbying_target_entities.csv",
              [{"government_entity_as_filed": k, "n_filings": v,
                "normalized_department": norm_agency(k)}
               for k, v in raw_targets.most_common()])
    return gap, fr_dept, lob_dept


# =====================================================================
# 4. THE CONSULTATION RECORD
# =====================================================================

# A first pass counted 2,795 "consultation notices" and was wrong. Every NAGPRA
# inventory notice contains the sentence "in consultation with the appropriate
# Indian Tribes or Native Hawaiian organizations" - which is evidence that
# consultation HAPPENED, but is not a notice announcing a consultation. Counting
# them together inflates the consultation record several-fold and would have
# been published as a finding.
#
# So two distinct measures, never summed:
#   notice   - the document's purpose is to convene or announce consultation
#   referenced - the document reports consultation already undertaken
CONSULT_TITLE = re.compile(r"\bconsultation\b|\bconsult(ing|s)?\b", re.I)
CONSULT_SUBJECT_ABS = re.compile(
    r"tribal consultation|consultation session|consultation meeting|"
    r"consultation (period|process|policy|framework|hearing)|"
    r"government-to-government consultation|"
    r"(will|to) (conduct|hold|convene|initiate)\w* .{0,40}consultation|"
    r"consult(ing|ation)? with (federally recognized |affected |interested )?"
    r"(indian )?trib(e|es|al)", re.I)
# The boilerplate that must not count as a consultation notice.
CONSULT_BOILERPLATE = re.compile(
    r"in consultation with the appropriate indian trib|"
    r"in consultation with the appropriate trib", re.I)


def build_consultation(fr_rows_raw, fr_out):
    print("\n[4] The consultation record")
    idx = {r["document_number"]: r for r in fr_out}
    rows, referenced = [], []
    for r in fr_rows_raw:
        o = idx.get(r.get("document_number", ""))
        if not o or not o["content_classifiable"]:
            continue
        t, a = r.get("title") or "", r.get("abstract") or ""
        boiler = bool(CONSULT_BOILERPLATE.search(a))
        in_title = bool(CONSULT_TITLE.search(t))
        in_abs = bool(CONSULT_SUBJECT_ABS.search(a)) and not boiler
        if boiler and not in_title:
            referenced.append({
                "document_number": r.get("document_number", ""),
                "publication_year": (r.get("publication_date") or "")[:4],
                "title": t,
                "agency_names": r.get("agency_names", ""),
                "basis": "abstract reports consultation already undertaken "
                         "(NAGPRA-style boilerplate); NOT a consultation notice",
            })
        if not (in_title or in_abs):
            continue
        rows.append({
            "document_number": r.get("document_number", ""),
            "publication_date": r.get("publication_date", ""),
            "publication_year": (r.get("publication_date") or "")[:4],
            "type": r.get("type", ""),
            "title": t,
            "agency_names": r.get("agency_names", ""),
            "normalized_departments": "|".join(sorted(
                {norm_agency(x.strip())
                 for x in (r.get("agency_names") or "").split("|") if x.strip()})),
            "consultation_signal": "title" if in_title else "abstract",
            "comment_url": r.get("comment_url", ""),
            "html_url": r.get("html_url", ""),
            "relevance_tier": o["relevance_tier"],
        })
    write_csv(CLEAN / "fr_consultation_notices.csv", rows)
    write_csv(CLEAN / "fr_consultation_referenced.csv", referenced)

    yc = Counter(r["publication_year"] for r in rows)
    rc = Counter(r["publication_year"] for r in referenced)
    dc = Counter(d for r in rows for d in r["normalized_departments"].split("|"))
    ser = [{"publication_year": y,
            "n_consultation_notices": yc.get(y, 0),
            "n_documents_reporting_consultation_undertaken": rc.get(y, 0)}
           for y in sorted(set(yc) | set(rc))]
    write_csv(CLEAN / "fr_consultation_year.csv", ser)

    write_csv(CLEAN / "fr_consultation_by_agency.csv",
              [{"normalized_department": k, "n_consultation_notices": v,
                "share_of_notices": round(v / len(rows), 4) if rows else ""}
               for k, v in dc.most_common()])
    print(f"  {len(rows):,} consultation NOTICES "
          f"(title-signal {sum(1 for r in rows if r['consultation_signal']=='title'):,}); "
          f"{len(referenced):,} documents merely REPORTING consultation")
    return rows, yc, dc


# =====================================================================
# 5. AUDITS - the accuracy numbers
# =====================================================================

AUDIT_LOBBY = CLEAN / "content_audit_lobbying_family.csv"
AUDIT_TIER = CLEAN / "content_audit_fr_relevance.csv"
AUDIT_THEME = CLEAN / "content_audit_fr_theme.csv"


def emit_audits(lob_rows, lob_filing, fr_rows_raw, fr_out):
    """Draw frozen-seed samples for hand coding. Never overwrites labelled work."""
    rnd = random.Random(AUDIT_SEED)

    if AUDIT_LOBBY.exists():
        print(f"  {AUDIT_LOBBY.name} exists - not overwriting")
    else:
        byid = {r["filing_uuid"]: r for r in lob_filing}
        pool = [r for r in lob_rows
                if (r.get("specific_issues_text") or "").strip()
                and r.get("filing_uuid") in byid]
        samp = rnd.sample(pool, min(N_AUDIT_LOBBY, len(pool)))
        write_csv(AUDIT_LOBBY, [{
            "filing_uuid": r["filing_uuid"],
            "filing_year": r.get("filing_year", ""),
            "client_name": r.get("client_name", ""),
            "specific_issues_text": re.sub(
                r"\s+", " ", html.unescape(html.unescape(
                    r.get("specific_issues_text") or "")))[:1200],
            "rule_families": byid[r["filing_uuid"]]["issue_families"],
            "hand_families": "",
            "hand_coder": "",
            "note": "",
        } for r in samp])

    if AUDIT_TIER.exists():
        print(f"  {AUDIT_TIER.name} exists - not overwriting")
    else:
        idx = {r["document_number"]: r for r in fr_out}
        strata = defaultdict(list)
        for r in fr_rows_raw:
            o = idx.get(r.get("document_number", ""))
            if o:
                strata[o["relevance_tier"]].append((r, o))
        per = {"title_subject": 40, "abstract_subject": 40,
               "weak_term_only": 15, "body_only_unverifiable": 25}
        samp = []
        for k, n in per.items():
            samp += rnd.sample(strata[k], min(n, len(strata[k])))
        write_csv(AUDIT_TIER, [{
            "document_number": r.get("document_number", ""),
            "publication_date": r.get("publication_date", ""),
            "rule_tier": o["relevance_tier"],
            "title": (r.get("title") or "")[:300],
            "abstract": re.sub(r"\s+", " ", (r.get("abstract") or ""))[:700],
            "agency_names": r.get("agency_names", ""),
            "hand_is_tribal_subject": "",
            "hand_coder": "",
            "note": "",
        } for r, o in samp])

    if AUDIT_THEME.exists():
        print(f"  {AUDIT_THEME.name} exists - not overwriting")
    else:
        idx = {r["document_number"]: r for r in fr_out}
        pool = [(r, idx[r["document_number"]]) for r in fr_rows_raw
                if r.get("document_number") in idx
                and idx[r["document_number"]]["content_classifiable"]]
        samp = rnd.sample(pool, min(N_AUDIT_FR_THEME, len(pool)))
        write_csv(AUDIT_THEME, [{
            "document_number": r.get("document_number", ""),
            "publication_date": r.get("publication_date", ""),
            "title": (r.get("title") or "")[:300],
            "abstract": re.sub(r"\s+", " ", (r.get("abstract") or ""))[:600],
            "rule_themes": o["themes"],
            "hand_themes": "",
            "hand_coder": "",
            "note": "",
        } for r, o in samp])


def _setify(s):
    return {x.strip() for x in (s or "").split("|") if x.strip()}


def score_multilabel(rows, rule_col, hand_col):
    """Per-item exact match plus micro precision/recall over labels."""
    done = [r for r in rows if (r.get(hand_col) or "").strip()]
    if not done:
        return None
    tp = fp = fn = exact = 0
    confusion = []
    for r in done:
        R, H = _setify(r[rule_col]), _setify(r[hand_col])
        if H == {"NONE"}:
            H = set()
        if R == H:
            exact += 1
        else:
            confusion.append(r)
        tp += len(R & H)
        fp += len(R - H)
        fn += len(H - R)
    prec = tp / (tp + fp) if tp + fp else 0.0
    rec = tp / (tp + fn) if tp + fn else 0.0
    return {
        "n_hand_coded": len(done),
        "exact_set_match": exact,
        "exact_set_match_rate": round(exact / len(done), 4),
        "label_precision": round(prec, 4),
        "label_recall": round(rec, 4),
        "label_f1": round(2 * prec * rec / (prec + rec), 4) if prec + rec else 0.0,
        "labels_true_positive": tp,
        "labels_false_positive": fp,
        "labels_false_negative": fn,
        "_confusion": confusion,
    }


def score_binary(rows, rule_col, hand_col, positive_tiers):
    done = [r for r in rows if (r.get(hand_col) or "").strip()]
    if not done:
        return None
    tp = tn = fp = fn = 0
    confusion = []
    for r in done:
        pred = r[rule_col] in positive_tiers
        truth = r[hand_col].strip().lower() in ("y", "yes", "1", "true")
        if pred and truth:
            tp += 1
        elif not pred and not truth:
            tn += 1
        elif pred and not truth:
            fp += 1
            confusion.append(r)
        else:
            fn += 1
            confusion.append(r)
    prec = tp / (tp + fp) if tp + fp else 0.0
    rec = tp / (tp + fn) if tp + fn else 0.0
    return {
        "n_hand_coded": len(done),
        "accuracy": round((tp + tn) / len(done), 4),
        "precision": round(prec, 4), "recall": round(rec, 4),
        "f1": round(2 * prec * rec / (prec + rec), 4) if prec + rec else 0.0,
        "tp": tp, "tn": tn, "false_positive": fp, "false_negative": fn,
        "_confusion": confusion,
    }


def score_stratified(rows, tier_counts, positive_tiers):
    """Reweight a stratified audit back to the corpus.

    The relevance sample deliberately oversamples the small tiers (40 of 9,523
    title_subject, but 25 of 132,964 body_only). Its raw accuracy is therefore a
    number about the SAMPLE, not about the corpus, and publishing it as a
    corpus error rate would overstate how wrong we are by a wide margin.
    Reweighting each stratum by its true size fixes that.
    """
    done = [r for r in rows if (r.get("hand_is_tribal_subject") or "").strip()]
    if not done:
        return None
    by = defaultdict(list)
    for r in done:
        by[r["rule_tier"]].append(r)
    tp = fp = fn = tn = 0.0
    per = []
    for tier, rs in by.items():
        N = tier_counts.get(tier, 0)
        if not rs or not N:
            continue
        w = N / len(rs)
        pred = tier in positive_tiers
        pos = sum(1 for r in rs
                  if r["hand_is_tribal_subject"].strip().lower() in ("y", "yes", "1"))
        neg = len(rs) - pos
        if pred:
            tp += pos * w
            fp += neg * w
        else:
            fn += pos * w
            tn += neg * w
        per.append({"tier": tier, "corpus_documents": N, "sampled": len(rs),
                    "hand_coded_tribal_subject": pos,
                    "stratum_positive_rate": round(pos / len(rs), 4)})
    tot = tp + fp + fn + tn
    prec = tp / (tp + fp) if tp + fp else 0.0
    rec = tp / (tp + fn) if tp + fn else 0.0
    return {
        "weighted_accuracy": round((tp + tn) / tot, 4) if tot else 0.0,
        "weighted_precision": round(prec, 4),
        "weighted_recall": round(rec, 4),
        "estimated_true_tribal_subject_documents": int(round(tp + fn)),
        "estimated_share_of_corpus": round((tp + fn) / tot, 4) if tot else 0.0,
        "flagged_classifiable": int(round(tp + fp)),
        "per_stratum": per,
    }


def run_audits(tier_counts=None):
    print("\n[5] Classifier accuracy (hand-audited)")
    out = []

    a = read_csv(AUDIT_LOBBY)
    s = score_multilabel(a, "rule_families", "hand_families")
    if s:
        out.append({"classifier": "lobbying_issue_family", "unit": "filing",
                    "sample_frame": "filings with non-empty specific_issues_text",
                    "sample_n": s["n_hand_coded"],
                    "metric_primary": "exact_set_match_rate",
                    "value_primary": s["exact_set_match_rate"],
                    "label_precision": s["label_precision"],
                    "label_recall": s["label_recall"],
                    "label_f1": s["label_f1"],
                    "n_disagreements": len(s["_confusion"]),
                    "audit_file": AUDIT_LOBBY.name})
        print(f"  lobbying families: exact-set {s['exact_set_match_rate']:.1%} "
              f"n={s['n_hand_coded']}, label P={s['label_precision']:.2f} "
              f"R={s['label_recall']:.2f}")
    else:
        print("  lobbying families: NOT YET HAND CODED")

    a = read_csv(AUDIT_TIER)
    s = score_binary(a, "rule_tier", "hand_is_tribal_subject",
                     {"title_subject", "abstract_subject"})
    if s:
        out.append({"classifier": "fr_relevance_tier", "unit": "document",
                    "sample_frame": "stratified across the four relevance tiers",
                    "sample_n": s["n_hand_coded"],
                    "metric_primary": "accuracy_stratified_sample",
                    "value_primary": s["accuracy"],
                    "label_precision": s["precision"],
                    "label_recall": s["recall"], "label_f1": s["f1"],
                    "n_disagreements": len(s["_confusion"]),
                    "audit_file": AUDIT_TIER.name})
        print(f"  FR relevance (raw stratified sample): acc {s['accuracy']:.1%} "
              f"P={s['precision']:.2f} R={s['recall']:.2f} n={s['n_hand_coded']}")
        if tier_counts:
            w = score_stratified(a, tier_counts,
                                 {"title_subject", "abstract_subject"})
            if w:
                out.append({
                    "classifier": "fr_relevance_tier_CORPUS_WEIGHTED",
                    "unit": "document",
                    "sample_frame": "same sample, reweighted to true tier sizes",
                    "sample_n": s["n_hand_coded"],
                    "metric_primary": "corpus_weighted_accuracy",
                    "value_primary": w["weighted_accuracy"],
                    "label_precision": w["weighted_precision"],
                    "label_recall": w["weighted_recall"],
                    "label_f1": "",
                    "n_disagreements": len(s["_confusion"]),
                    "audit_file": AUDIT_TIER.name,
                    "estimated_true_tribal_subject_documents":
                        w["estimated_true_tribal_subject_documents"],
                    "estimated_share_of_corpus": w["estimated_share_of_corpus"],
                })
                write_csv(CLEAN / "fr_relevance_stratum_audit.csv", w["per_stratum"])
                print(f"  FR relevance (corpus-weighted): acc "
                      f"{w['weighted_accuracy']:.1%} P={w['weighted_precision']:.2f} "
                      f"R={w['weighted_recall']:.2f}; estimated "
                      f"{w['estimated_true_tribal_subject_documents']:,} truly "
                      f"tribal-subject documents "
                      f"({w['estimated_share_of_corpus']:.1%} of corpus)")
    else:
        print("  FR relevance: NOT YET HAND CODED")

    a = read_csv(AUDIT_THEME)
    s = score_multilabel(a, "rule_themes", "hand_themes")
    if s:
        out.append({"classifier": "fr_theme", "unit": "document",
                    "sample_frame": "random within classifiable (title/abstract-subject) docs",
                    "sample_n": s["n_hand_coded"],
                    "metric_primary": "exact_set_match_rate",
                    "value_primary": s["exact_set_match_rate"],
                    "label_precision": s["label_precision"],
                    "label_recall": s["label_recall"],
                    "label_f1": s["label_f1"],
                    "n_disagreements": len(s["_confusion"]),
                    "audit_file": AUDIT_THEME.name})
        print(f"  FR themes: exact-set {s['exact_set_match_rate']:.1%} "
              f"P={s['label_precision']:.2f} R={s['label_recall']:.2f} "
              f"n={s['n_hand_coded']}")
    else:
        print("  FR themes: NOT YET HAND CODED")

    for r in out:
        r["hand_coder"] = "agent (Claude), published for human review"
        r["audit_date"] = TODAY
        r["seed"] = AUDIT_SEED
    if out:
        write_csv(CLEAN / "content_analysis_accuracy.csv", out)
    return out


# =====================================================================
# 6. CORPUS DIAGNOSTICS - and the NAGPRA series the theme classifier gets wrong
# =====================================================================
#
# The theme series showed NAGPRA collapsing from ~80/yr in 2002 to ~17/yr for
# 2003-2010, then exploding after 2011. That is not what happened. Before 2011
# almost NO NAGPRA notice in this corpus carries an abstract (0-5 a year), and
# their titles - "Notice of Inventory Completion: Beloit College, Beloit, WI" -
# contain no Native term. So they land in body_only_unverifiable and never reach
# the theme classifier at all. The trough is an artefact of abstract
# availability interacting with the relevance tier.
#
# The fix is not to re-tune the tier rule (that would invalidate the audit) but
# to classify NAGPRA on the one signal that is present throughout: the FR's own
# standardised notice titles. "Notice of Inventory Completion" IS a NAGPRA
# notice - the phrase is prescribed by 43 CFR 10.9. Precision is near-total and
# it does not depend on an abstract existing.
#
# Rule: use THIS series for NAGPRA over time. The theme series is unusable
# before 2011 for this theme, and the same abstract gap makes every pre-2011
# theme count a floor rather than a level.
#
# FILENAME NOTE (2026-08-06): these outputs were originally written to
# `nagpra_notices.csv`, which silently clobbered a concurrent agent's far richer
# NAGPRA build (institution parsing, MNI counts, resolved entity IDs). Caught
# only because a row count read back 1,180 against the 6,606 written. Renamed to
# `fr_nagpra_title_index*`. This file is a title-based INDEX of the parent FR
# corpus, not the NAGPRA product - see `nagpra_notices.csv` for that. Do not
# rename it back.

NAGPRA_TITLE = re.compile(
    r"notice of inventory completion|notice of intent to repatriate|"
    r"notice of intended repatriation|notice of intent to repatriate cultural",
    re.I)


def build_diagnostics(fr_rows_raw, fr_out):
    print("\n[6] Corpus diagnostics and the corrected NAGPRA series")
    idx = {r["document_number"]: r for r in fr_out}

    nag, per_year = [], defaultdict(lambda: [0, 0])
    for r in fr_rows_raw:
        t = r.get("title") or ""
        if not NAGPRA_TITLE.search(t):
            continue
        y = (r.get("publication_date") or "")[:4]
        has_abs = bool((r.get("abstract") or "").strip())
        o = idx.get(r.get("document_number", ""))
        per_year[y][0] += 1
        if has_abs:
            per_year[y][1] += 1
        nag.append({
            "document_number": r.get("document_number", ""),
            "publication_date": r.get("publication_date", ""),
            "publication_year": y,
            "title": t,
            "agency_names": r.get("agency_names", ""),
            "notice_kind": ("inventory_completion"
                            if re.search(r"inventory completion", t, re.I)
                            else "intent_to_repatriate"),
            "has_abstract": int(has_abs),
            "relevance_tier_from_tier_rule":
                o["relevance_tier"] if o else "",
            "missed_by_tier_rule":
                int(bool(o) and not o["content_classifiable"]),
            "basis": "FR standardised notice title prescribed by 43 CFR 10; "
                     "does not depend on abstract availability",
        })
    write_csv(CLEAN / "fr_nagpra_title_index.csv", nag)
    write_csv(CLEAN / "fr_nagpra_title_index_year.csv",
              [{"publication_year": y,
                "n_nagpra_notices": per_year[y][0],
                "n_with_abstract": per_year[y][1],
                "share_with_abstract": round(per_year[y][1] / per_year[y][0], 4)
                if per_year[y][0] else ""}
               for y in sorted(per_year) if y])
    missed = sum(r["missed_by_tier_rule"] for r in nag)
    print(f"  {len(nag):,} NAGPRA notices by title; {missed:,} "
          f"({100*missed/len(nag):.1f}%) were missed by the relevance tier rule")

    # Abstract availability is the single biggest determinant of what we can
    # classify at all, so it is published as a series in its own right.
    ab = defaultdict(lambda: [0, 0])
    for r in fr_rows_raw:
        y = (r.get("publication_date") or "")[:4]
        if not y:
            continue
        ab[y][0] += 1
        if (r.get("abstract") or "").strip():
            ab[y][1] += 1
    write_csv(CLEAN / "fr_abstract_availability_year.csv",
              [{"publication_year": y, "n_documents": ab[y][0],
                "n_with_abstract": ab[y][1],
                "share_with_abstract": round(ab[y][1] / ab[y][0], 4)}
               for y in sorted(ab)])
    return nag, missed


def main():
    print("=== Cedar Press 78: content analysis ===")
    lob_rows = read_csv(LOBBY)
    fr_rows = read_csv(FR)
    print(f"lobbying {len(lob_rows):,} filings | FR {len(fr_rows):,} documents")

    lob_filing, seg_status, year_total, coded_year, fam_year = build_lobbying(lob_rows)
    fr_out, tiers, theme_year, class_year, agency_year, agency_theme = build_fr(fr_rows)

    if "--emit-audit" in sys.argv:
        print("\n[audit] emitting hand-coding samples")
        emit_audits(lob_rows, lob_filing, fr_rows, fr_out)
        return

    build_agencies(fr_out, lob_rows, agency_year)
    build_consultation(fr_rows, fr_out)
    build_diagnostics(fr_rows, fr_out)
    run_audits(tier_counts=dict(tiers))

    stats = {
        "generated": TODAY,
        "lobbying_filings": len(lob_rows),
        "lobbying_filings_with_text": sum(
            1 for r in lob_rows if (r.get("specific_issues_text") or "").strip()),
        "lobbying_segment_outcomes": dict(seg_status),
        "fr_documents": len(fr_rows),
        "fr_relevance_tiers": dict(tiers),
        "fr_classifiable": tiers["title_subject"] + tiers["abstract_subject"],
    }
    (CLEAN / "_content_analysis_stats.json").write_text(
        json.dumps(stats, indent=2), encoding="utf-8")
    print("\nwrote _content_analysis_stats.json")


if __name__ == "__main__":
    main()
