"""Bounded research previews from hash-pinned producer packets and current release gates.

Packets are generated by Lumecon-data's release_usability full scan. This consumer
never samples an arbitrary source file and never exposes the packet's internal directory.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
from pathlib import Path

from cedar_press import customer_sheet, repository, source_presentation

MAX_PACKET_BYTES = 8 * 1024 * 1024
PRIVATE_FIELDS = frozenset(
    {
        "source_inbox",
        "source_files",
        "link_ledger_source_file",
        "source_dataset",
        "raw_path",
        "storage_path",
        "referenced_path",
    }
)
PRIVATE_PATH = re.compile(
    r'(?:^|[\s("\'])' r"(?:[A-Za-z]:[\\/]|~[/\\]|/(?:Users|home|mnt|tmp)/|file://|\\\\)"
)
CREDENTIAL_URL = re.compile(
    r"://[^/\s]*@|[?&](?:api[_-]?key|access[_-]?token|token|password|signature|sig|x-amz-[^=]*)=",
    re.I,
)
CODEBOOK_FIELDS = frozenset(
    {
        "name",
        "label",
        "definition",
        "type",
        "unit",
        "research_unit",
        "storage_unit",
        "row_grain",
        "temporal_meaning",
        "allowed_values",
        "missing_values",
        "missing_meaning",
        "missing_count",
        "missing_fraction",
        "source_field",
        "derivation",
        "display_disposition",
        "rights_class",
        "permitted_review_preview",
        "nullable",
        "missingness",
        "source_fields",
        "source_field_basis",
        "definition_status",
        "definition_source",
        "display_reason",
        "unit_source",
        "key_member",
    }
)


def _read(path: Path, expected: str | None = None):
    if path.is_symlink() or not path.is_file() or path.stat().st_size > MAX_PACKET_BYTES:
        raise repository.FullReleaseUnavailable("Research artifact unavailable")
    raw = path.read_bytes()
    if expected is not None and (
        not re.fullmatch(r"[0-9a-f]{64}", expected) or hashlib.sha256(raw).hexdigest() != expected
    ):
        raise repository.FullReleaseUnavailable("Research artifact checksum mismatch")
    return json.loads(raw)


def _public_value(value):
    if isinstance(value, str):
        return None if PRIVATE_PATH.search(value) or CREDENTIAL_URL.search(value) else value
    if isinstance(value, list):
        return [_public_value(item) for item in value]
    if isinstance(value, dict):
        return {
            key: _public_value(item) for key, item in value.items() if key not in PRIVATE_FIELDS
        }
    return value


def packet(tier: str, collection: str, release_id: str, component: str | None = None) -> dict:
    """The caller resolves a live account; shared release policy remains authoritative."""
    if not repository.may_download_full(tier, collection):
        raise repository.FullReleaseUnavailable("Collection not included")
    if not re.fullmatch(r"[a-z][a-z0-9-]{0,63}", collection) or not re.fullmatch(
        r"[0-9a-f]{64}", release_id
    ):
        raise repository.FullReleaseUnavailable("Invalid research release identity")
    repository.assert_collection_publishable(collection)
    if repository.is_component_release(collection) and not (
        collection == "federal-register" and component is None
    ):
        release = repository.grove_full_release(
            collection, release_id, component=component, metadata_only=True
        )
    else:
        if component is not None:
            raise repository.FullReleaseUnavailable("Native release has no selectable component")
        release = repository.full_release(collection, release_id, metadata_only=True)
    if release.get("release_id") != release_id:
        raise repository.FullReleaseUnavailable("Research release differs from current pin")
    configured = os.environ.get("CEDAR_PRESS_RESEARCH_CATALOG")
    if not configured:
        raise repository.FullReleaseUnavailable("Research packet not configured")
    catalog_path = Path(configured)
    catalog = _read(catalog_path)
    if catalog.get("review_only") is True and os.environ.get("CEDAR_PRESS_ENVIRONMENT") not in {
        "development",
        "staging",
    }:
        raise repository.FullReleaseUnavailable("Review research catalog refused in production")
    registration = catalog.get("packets", {}).get(collection)
    if not isinstance(registration, dict) or registration.get("release_id") != release_id:
        raise repository.FullReleaseUnavailable("Research packet not pinned to this release")
    relative = registration.get("directory")
    if not isinstance(relative, str) or not re.fullmatch(r"[A-Za-z0-9_/-]+", relative):
        raise repository.FullReleaseUnavailable("Invalid research packet location")
    root = catalog_path.parent.resolve()
    directory = (root / relative).resolve()
    if not directory.is_relative_to(root) or directory.is_symlink():
        raise repository.FullReleaseUnavailable("Research packet leaves configured store")
    receipt_digest = registration.get("receipt_sha256")
    if not isinstance(receipt_digest, str) or not re.fullmatch(r"[0-9a-f]{64}", receipt_digest):
        raise repository.FullReleaseUnavailable("Missing research receipt pin")
    receipt = _read(directory / "receipt.json", receipt_digest)
    if (
        receipt.get("collection") != collection
        or receipt.get("release_id") != release_id
        or receipt.get("synthetic") is not False
        or receipt.get("schema_version") != 1
        or receipt.get("consumer_manifest_sha256") != release.get("manifest_sha256")
    ):
        raise repository.FullReleaseUnavailable("Research receipt identity mismatch")
    if receipt.get("release_class") == "rehearsal" and os.environ.get(
        "CEDAR_PRESS_ENVIRONMENT"
    ) not in {"development", "staging"}:
        raise repository.FullReleaseUnavailable("Review research packet refused in production")
    declarations = _read(
        directory / "consumer-declarations.json",
        receipt.get("artifacts", {}).get("consumer-declarations.json", ""),
    )
    candidates = declarations.get("components", {})
    logical = component or (next(iter(candidates)) if len(candidates) == 1 else "")
    if not re.fullmatch(r"[a-z0-9][a-z0-9_]{0,59}", logical):
        raise repository.FullReleaseUnavailable("Invalid research component")
    artifacts = receipt.get("artifacts", {})

    def artifact(name):
        digest = artifacts.get(name)
        if not isinstance(digest, str):
            raise repository.FullReleaseUnavailable("Research artifact missing from receipt")
        return _read(directory / name, digest)

    preview = artifact(logical + ".preview.json")
    codebook = artifact("codebook.json").get(logical)
    declaration = candidates.get(logical)
    if (
        not isinstance(codebook, dict)
        or not isinstance(declaration, dict)
        or declaration.get("order") != release["fields"]
        or preview.get("collection") != collection
        or preview.get("release_id") != release_id
        or preview.get("component") != logical
        or preview.get("scope") not in {"permitted_review_preview", "permitted_release_preview"}
        or preview.get("source_rows") != release["record_count"]
    ):
        raise repository.FullReleaseUnavailable(
            "Research schema, rights or count differs from release"
        )
    sample = preview.get("rows")
    if not isinstance(sample, list) or not 0 < len(sample) <= 30:
        raise repository.FullReleaseUnavailable("Research preview lacks bounded real examples")
    fields = codebook.get("fields", [])
    names = {field["name"] for field in fields if field.get("permitted_review_preview")}
    if names != set(release["fields"]):
        raise repository.FullReleaseUnavailable("Research fields are held or undeclared")
    verified = []
    for selected in sample:
        row = selected.get("row")
        if not isinstance(row, dict) or set(row) != names:
            raise repository.FullReleaseUnavailable("Preview row schema differs from release")
        if hashlib.sha256(repository._canonical_bytes(row)).hexdigest() != selected.get(
            "selection_sha256"
        ):
            raise repository.FullReleaseUnavailable("Preview row checksum mismatch")
        verified.append(row)
    # Verified first, then presented under the owner's rules of 2026-10-04:
    # Cedar IDs and listed public registry IDs only, public sources only, no
    # version labels. The packet and its hashes are unchanged.
    by_name = {field["name"]: field for field in fields}
    header, presented, _report = customer_sheet.present_rows(
        collection,
        [{"name": name, "type": by_name.get(name, {}).get("type")} for name in release["fields"]],
        verified,
    )
    renamed = {**customer_sheet.VERSION_RENAMES}
    shown = set(header)
    rows = []
    for selected, row in zip(sample, presented, strict=True):
        public_row = _public_value(row)
        rows.append(
            {
                "row": public_row,
                "source": source_presentation.present(collection, public_row, component),
                "source_part": selected["component"],
                "release_row_sha256": selected["selection_sha256"],
                "temporal_bucket": selected["temporal_bucket"],
            }
        )
    result = {
        "kind": "verified_release_research",
        "collection": collection,
        "release_id": release_id,
        "component": component,
        "scope": preview["scope"],
        "source_rows": preview["source_rows"],
        "sample_rows": len(rows),
        "rows": rows,
        "display_order": [
            renamed.get(name, name)
            for name in declaration.get("display_order", release["fields"])
            if name not in PRIVATE_FIELDS and renamed.get(name, name) in shown
        ],
        "codebook": {
            "row_grain": codebook["row_grain"],
            "primary_key": [name for name in codebook["primary_key"] if name in shown],
            "fields": [
                _public_value(
                    {
                        **{key: value for key, value in field.items() if key in CODEBOOK_FIELDS},
                        "name": renamed.get(field["name"], field["name"]),
                    }
                )
                for field in fields
                if field["name"] not in PRIVATE_FIELDS
                and renamed.get(field["name"], field["name"]) in shown
            ],
            "temporal_fields": _public_value(codebook.get("temporal_fields", {})),
            "aggregation_cautions": _public_value(codebook.get("aggregation_cautions", [])),
        },
        "provenance": {
            "manifest_file_sha256": receipt["manifest_file_sha256"],
            "consumer_manifest_sha256": receipt["consumer_manifest_sha256"],
            "packet_receipt_sha256": registration["receipt_sha256"],
            "sample_artifact_sha256": artifacts[logical + ".preview.json"],
            "generator_sha256": receipt.get("generator_sha256"),
            "method": receipt["method"],
        },
        "limits": [
            "Representative examples do not establish complete coverage.",
            "An absent original publisher or document remains a provenance gap.",
            "Internal path values are omitted from display; the stable export schema is unchanged.",
        ],
    }
    map_artifact = logical + ".map.json"
    if collection == "plot" and map_artifact in artifacts:
        from cedar_press import plot_map

        result["map_preview"] = plot_map.present(
            _public_value(artifact(map_artifact)),
            release_id=release_id,
            component=logical,
            scope=preview["scope"],
            source_rows=preview["source_rows"],
            selected=rows,
        )
        result["provenance"]["map_artifact_sha256"] = artifacts[map_artifact]
    if len(repository._canonical_bytes(result)) > 4 * 1024 * 1024:
        raise repository.FullReleaseUnavailable("Research response exceeds boundary size")
    return result
