# -*- coding: utf-8 -*-
"""Writes docs/ANCSA_PORTAL_BUILD_LOG.md from the harvested artefacts."""
import csv, json, os
from collections import Counter
from pathlib import Path

HERE = os.path.dirname(os.path.abspath(__file__))
CP = str(Path(__file__).resolve().parent.parent.parent)
idx = list(csv.DictReader(open(os.path.join(CP, "data", "clean", "ancsa_filings_index.csv"), encoding="utf-8-sig")))
man = list(csv.DictReader(open(os.path.join(CP, "data", "raw", "external", "ancsa_portal", "_SOURCE_MANIFEST.csv"), encoding="utf-8-sig")))
deals = list(csv.DictReader(open(os.path.join(CP, "data", "clean", "deals_ancsa_portal_additions.csv"), encoding="utf-8-sig")))
skip = list(csv.DictReader(open(os.path.join(CP, "review", "deals_skipped_ancsa_portal.csv"), encoding="utf-8-sig")))
roster = list(csv.DictReader(open(os.path.join(CP, "data", "clean", "anc_ceiling_roster.csv"), encoding="utf-8-sig")))
corps = json.load(open(os.path.join(HERE, "corps.json")))
cen = json.load(open(os.path.join(HERE, "year_census.json")))
done = json.load(open(os.path.join(HERE, "index_done.json")))

cat = Counter(r["document_type"] for r in idx)
yr = Counter(r["period_covered"] for r in idx)
corp_doc = Counter()
for r in idx:
    for c in r["corporation_name"].split("; "):
        corp_doc[c] += 1
matched = sum(1 for r in idx if r["anc_id"])
regional = {r["corporation_name"] for r in roster if r["anc_class"] == "ANC_REGIONAL"}
rmap = {r["corporation_name"]: r["anc_class"] for r in roster}
cls = Counter()
for r in idx:
    for c in set(r["anc_class"].split("; ")):
        if c:
            cls[c] += 1
ids_in_portal = {r["anc_id"] for r in idx for _ in [0] if r["anc_id"]}
ids_in_portal = set()
for r in idx:
    for a in r["anc_id"].split("; "):
        if a:
            ids_in_portal.add(a)
roster_cls = Counter(r["anc_class"] for r in roster)
covered_cls = Counter(r["anc_class"] for r in roster if r["anc_id"] in ids_in_portal)

dl_bytes = sum(int(r["bytes"]) for r in man if r["bytes"])
noext = sum(1 for r in man if r["text_extractable"] == "no_image_only")
dyear = Counter(d["Event_Year"] for d in deals)
dparty = Counter(d["Native_Party"] for d in deals)
dconf = Counter(d["Confidence"] for d in deals)
exact = sum(1 for d in deals if "MONTH-LEVEL" not in d["Date_Basis"])
valued = [d for d in deals if d["Announced_Value_USD"]]
total_val = sum(float(d["Announced_Value_USD"]) for d in valued)
skipr = Counter(s["Skip_Reason"] for s in skip)

def tbl(counter, keyname, order=None):
    keys = order or sorted(counter)
    return "\n".join("| %s | %s |" % (k, format(counter[k], ",")) for k in keys if k in counter)

yrs_order = [y for y in sorted(cen, key=int) if cen[y]]

L = []
w = L.append
w("# ANCSA Portal Build Log — Alaska DBS STAR, harvested 2026-08-05")
w("")
w("Dataset 1 (Indian Country Deals). Source: the Alaska Department of Commerce, Community and")
w("Economic Development, Division of Banking and Securities STAR portal, which holds ANCSA")
w("corporation filings made under AS 45.55.139. Access was granted to Elijah by the Division")
w("(\"the ANCSA portal is live and you are now able to view and retrieve documents on your own\").")
w("")
w("**Outputs**")
w("- `data/raw/external/ancsa_portal/` — %s PDFs (%.2f GB) + `_SOURCE_MANIFEST.csv`" % (format(len(man), ","), dl_bytes / 1024 ** 3))
w("- `data/clean/ancsa_filings_index.csv` — **%s documents**, one row per document, downloaded or not" % format(len(idx), ","))
w("- `data/clean/deals_ancsa_portal_additions.csv` — **%d deal rows**" % len(deals))
w("- `review/deals_skipped_ancsa_portal.csv` — **%d skipped leads**" % len(skip))
w("- Log: `logs/29_ancsa_portal.log` (access method, search contract, year census, HB126 text)")
w("")
w("Nothing was written into `deals_2026_ytd.csv`, `deals_historical_2020_2025.csv`, `data/spine/`,")
w("`data/clean/cedar_*` or `review/cedar_review*.html`. Schema of the additions file was validated")
w("column-for-column against `deals_historical_2020_2025.csv` (32 columns, identical order).")
w("Deal_IDs use the reserved prefix `ANCSA-` and were checked against both live ledgers and all")
w("three existing additions files: **zero collisions**, zero internal duplicates.")
w("")
w("---")
w("")
w("## 1. The access method that worked (this is the reusable part)")
w("")
w("The entry points named in the brief are a dead end for retrieval, and the reason is worth")
w("recording precisely.")
w("")
w("1. `https://portal.akdbsstar.us/StarWebPortal/` → 302 → `/page/default/portal.aspx`, HTTP 200,")
w("   issues an `ASP.NET_SessionId`.")
w("2. `/UIPViews/FillXPForm.aspx` fetched directly returns HTTP 500, as previously established.")
w("3. The root page exposes exactly two `__doPostBack` actions: **Search ANCSA Filings** and")
w("   **Submit ANCSA Documents**.")
w("4. POSTing the *Search ANCSA Filings* action does land on `FillXPForm.aspx` with HTTP 200 — but")
w("   that page is titled **\"Application - Public Record Request (Web)\"**. It is a REQUEST INTAKE")
w("   WIZARD: last name, first name, firm, mailing address, phone, email, a free-text")
w("   \"File(s) Requested\" box, and a Next button. It is not a document index. **Nothing was")
w("   submitted through it.** No personal data was transmitted and no records request was filed;")
w("   filing a request in Elijah's name is a human decision, not an agent decision.")
w("5. The actual self-service search is a different page that is **not linked from the root action")
w("   list** and whose URL path is **case-sensitive**:")
w("")
w("   ```")
w("   https://portal.akdbsstar.us/StarWebPortal/page/ANCSA/portal.aspx    <- the search page")
w("   https://portal.akdbsstar.us/StarWebPortal/page/ancsa/portal.aspx    <- 200, but renders EMPTY")
w("   ```")
w("")
w("   Lowercase returns the site chrome with no search control at all, which reads exactly like a")
w("   page that does not exist. This one capital letter is the whole difference between \"the portal")
w("   has no public search\" and 19,269 retrievable documents.")
w("")
w("### Search contract")
w("")
w("POST to the same URL. Field prefix `P = ctl00$ContentPlaceholder1$PortalPageControl1$ctl26$`:")
w("")
w("| Field | Values |")
w("|---|---|")
w("| `P+ddCorporationName` | one of 60 exact strings, or `-----Select Corporation Name-----` (= all) |")
w("| `P+ddDocumentCategory` | `ANCSA Annual Report`, `ANCSA Independent Candidate Proxy Materials`, `ANCSA Proxy Materials`, `ANCSA Proxy Statement`, or the `-----Select...-----` placeholder (= all) |")
w("| `P+txtYear` | **required**; RangeValidator 1900–2100. A blank year returns zero rows with `* Invalid year.` **There is no all-years search.** |")
w("| `P+btnSubmit` | `Submit` |")
w("")
w("Hidden fields on this portal are `__EVENTTARGET`, `__EVENTARGUMENT`, `__VIEWSTATE`,")
w("`__VIEWSTATE1`, `__VIEWSTATEENCRYPTED`. There is **no `__VIEWSTATEGENERATOR` and no")
w("`__EVENTVALIDATION`** — echo whatever hidden inputs the previous response carried.")
w("")
w("Results grid `ctl00_ContentPlaceholder1_PortalPageControl1_ctl26_gvFileList`: 25 rows per page,")
w("columns *Document Description | Year | Category*. **There is no corporation column and no filing-date")
w("column.** Pagination is `__EVENTTARGET=<grid id>`, `__EVENTARGUMENT=Page$N`. The result count is in")
w("`..._lblGridPosition` (\"Displaying record 1 to 25 of 1534\").")
w("")
w("Documents download from `https://portal.akdbsstar.us/StarWebPortal/ViewFile.aspx?Id=<GUID>`,")
w("`application/pdf`, no `Content-Disposition`, same session cookie. **The href emitted in the grid")
w("is malformed**: the GUID is immediately followed by the literal text `rel=\"noreferrer\"` with no")
w("separator. Parse the GUID with a `[0-9a-fA-F-]{36}` regex; do not take the href verbatim.")
w("")
w("### Throughput trap that cost about forty minutes")
w("")
w("Re-fetching `page/ANCSA/portal.aspx` with a GET before every search made a single search take")
w("25–45 seconds. Reusing the hidden fields from the **previous POST response** and chaining POSTs on")
w("one session brings a search to 1.2–2.1 seconds. Throttle used: 1.0 s between requests, one")
w("connection, sequential. 171 document downloads were throttled at 4 s. No error responses were")
w("returned by the portal at any point, and no request was retried more than once.")
w("")
w("---")
w("")
w("## 2. What is actually in the portal")
w("")
w("### Year census (one page-1 search per year, 1971–2026)")
w("")
w("Every year from 1971 to 2011 and the years 2013, 2014 and 2015 return **zero documents**. These")
w("are valid queries — the year validator accepts 1900–2100 — so the zeros are real absences, not")
w("rejected searches.")
w("")
w("| Year | Documents |")
w("|---|---|")
for y in yrs_order:
    w("| %s | %s |" % (y, format(cen[y], ",")))
w("| **Total** | **%s** |" % format(sum(cen[y] for y in yrs_order), ","))
w("")
w("**The portal's effective coverage floor is 2016.** The two 2012 documents are strays. This is a")
w("live filing system, not a historical archive: it does not reach the 1970s–2000s ANCSA filings at")
w("all, and the pre-2016 deal history this project wants has to come from somewhere else.")
w("")
w("### By document type (%s indexed documents)" % format(len(idx), ","))
w("")
w("| Category | Documents |")
w("|---|---|")
for k, v in cat.most_common():
    w("| %s | %s |" % (k, format(v, ",")))
w("")
_ar = 100.0 * cat.get("ANCSA Annual Report", 0) / max(1, len(idx))
w("Annual reports are about %.0f%% of the portal by count. The other ~%.0f%% is shareholder-election" % (_ar, 100.0 - _ar))
w("material — proxy cards, candidate statements, meeting notices, solicitation letters. That is a")
w("governance corpus, not a transaction corpus, and it should not be mined for deal rows. It is,")
w("however, a strong seed for a future ANC board/elections dataset, and the index built here already")
w("enumerates all of it by corporation and year.")
w("")
w("A caution for anyone filtering on category: **the Division's `ANCSA Annual Report` category is not")
w("purely annual reports.** It also carries settlement-trust financial statements, consolidated")
w("financial statements filed separately from the report, and — in NANA's 2018 filings — annual-meeting")
w("posters, postcards, envelopes and a prize card. Filter on category to find candidates, then read.")
w("")
w("### By year")
w("")
w("| Year | Documents indexed |")
w("|---|---|")
for y in sorted(yr, key=lambda s: (s.isdigit() is False, s)):
    w("| %s | %s |" % (y, format(yr[y], ",")))
w("")
w("### Index completeness")
w("")
_cells = len(done)
_total = len(corps) * len(yrs_order)
if _cells >= _total:
    w("The index was built by running **every one of the %d corporation x year searches** (%d corporations" % (_total, len(corps)))
    w("x %d years with documents). It is complete." % len(yrs_order))
else:
    _miss = sorted({(c, y) for c in corps for y in yrs_order} - {tuple(k.split("||")) for k in done})
    _my = Counter(y for _, y in _miss)
    w("**%s of %s corporation x year searches were run (%.1f%%).** The %d outstanding cells are all in" % (
        format(_cells, ","), format(_total, ","), 100.0 * _cells / _total, len(_miss)))
    w("year(s) %s and can be completed by re-running `code/ancsa_portal/full_index.py`, which is" % ", ".join(sorted(_my)))
    w("resumable from `code/ancsa_portal/index_done.json`. Everything already indexed is final.")
w("")
w("---")
w("")
w("## 3. Coverage against the 196-entry ANC roster")
w("")
w("The portal's corporation dropdown holds **%d corporations**. Every one of them matched a row in" % len(corps))
w("`data/clean/anc_ceiling_roster.csv` (%d entries) after Unicode normalisation — the only non-trivial" % len(roster))
w("match was *Ukpeagvik Inupiat Corporation* in the portal against *Ukpeaġvik Iñupiat Corporation* in")
w("the roster. So corporation attribution in the index is **%s of %s document rows carrying an anc_id**." % (format(matched, ","), format(len(idx), ",")))
w("")
w("| Roster class | On roster | Present in the portal |")
w("|---|---|---|")
for k in ["ANC_REGIONAL", "ANC_VILLAGE", "ANC_URBAN"]:
    w("| %s | %d | %d |" % (k, roster_cls.get(k, 0), covered_cls.get(k, 0)))
w("| **Total** | **%d** | **%d** |" % (len(roster), len(ids_in_portal)))
w("")
w("**%d of 196 roster entries (%.0f%%) appear in this source.** That number should not be read as a" % (len(ids_in_portal), 100.0 * len(ids_in_portal) / len(roster)))
w("failure of the harvest, and the Division said so before the harvest started:")
w("")
w("- Filing under AS 45.55.139 is **conditional**, not universal. Only corporations meeting the")
w("  statutory test file at all. The remaining roster entries are largely small village corporations")
w("  that have never been filers.")
w("- **Some corporations will not have annual reports at all**, depending on when their annual meeting")
w("  falls (Division's own caveat). An absent report is not a missing document.")
w("- **HB126 shrank the filer population further as of 2026-06-25** (section 5 below). The 60-name")
w("  dropdown captured on 2026-08-05 is already a post-HB126 list.")
w("")
w("Twelve of the thirteen ANCSA **regional** corporations are present. The absentee is **The 13th")
w("Regional Corporation**, organised for Alaska Natives resident outside Alaska; it is not in the")
w("dropdown. Absence from the dropdown is evidence that it is not a current filer, not evidence that")
w("no filings exist. Do not claim \"all thirteen regionals\" from this source.")
w("")
w("### Documents per corporation — top 15")
w("")
w("| Corporation | Documents |")
w("|---|---|")
for c, n in corp_doc.most_common(15):
    w("| %s | %s |" % (c.strip(), format(n, ",")))
w("")
w("Every one of the 60 portal corporations returned at least one document.")
w("")
w("---")
w("")
w("## 4. Deal rows extracted")
w("")
w("**%d rows**, all from ANCSA annual reports retrieved in this run, %d of them with an exact" % (len(deals), exact))
w("day-level transaction date stated in the filing and %d with a month-level date only. %d rows carry" % (len(deals) - exact, len(valued)))
w("a value; the sum of `Announced_Value_USD` as written is **$%.2f billion**." % (total_val / 1e9))
w("")
w("| Year | Rows | | Native party | Rows |")
w("|---|---|---|---|---|")
ys = sorted(dyear)
ps = dparty.most_common()
for i in range(max(len(ys), len(ps))):
    a = "| %s | %d " % (ys[i], dyear[ys[i]]) if i < len(ys) else "| | "
    b = "| %s | %d |" % (ps[i][0], ps[i][1]) if i < len(ps) else "| | |"
    w(a + b)
w("")
w("Confidence: %s." % ", ".join("%d %s" % (v, k) for k, v in dconf.most_common()))
w("")
w("### Where the value is")
w("")
w("Arctic Slope Regional Corporation alone accounts for %d of the %d rows. ASRC's annual reports carry" % (dparty.get("Arctic Slope Regional Corporation", 0), len(deals)))
w("a full acquisitions note with a per-target purchase-price table AND a narrative giving the month and")
w("the price for each target. Nobody else in the corpus documents transactions that systematically.")
w("The single largest row is **ASRC Federal's acquisition of Vistronix on 16 August 2016 for")
w("$182,500,000** (ANCSA-2016-004).")
w("")
w("### What this seam is good for")
w("")
w("The prior 2000–2019 build log named **2010–2017 the true soft spot** of the ledger, at roughly one")
w("row per year, and named ANC annual reports as the channel that should cover it and had")
w("underperformed. This run puts **%d rows into 2012–2019**, which is more than the entire 2010–2017" % sum(v for k, v in dyear.items() if "2012" <= k <= "2019"))
w("stretch produced in the previous sweep. The seam the earlier log identified was real, and the")
w("obstacle was never the source — it was not knowing the URL had a capital A.")
w("")
w("### Deduplication and restatement")
w("")
w("Annual reports restate the same transaction for three to five years running. Deduplication was done")
w("on the **transaction**, never on the mention, and every restatement is flagged in `Notes`. Worked")
w("examples in the file: Chugach's Rex Electric acquisition appears in the 2016, 2017 and 2018 reports")
w("(one row); Sealaska's Odyssey purchase appears as a 2016 subsequent event, a 2017 note and a 2018")
w("restatement (one row); Ahtna's AAA Valley Gravel appears in 2016 and again in the 2018 cash-flow")
w("disclosures (one row); Chugach's VPSI purchase appears in the 2024 and 2025 reports (one row).")
w("")
w("Rows are filed by **transaction year, not report year**. ANCSA-2014-001 (ASRC/Little Red Services,")
w("May 2014) was recovered from the 2016 annual report; ANCSA-2012-001 and -002 (CIRI/Cruzco and")
w("CIRI/Weldin, March 2012) were recovered from the 2016 annual report four years after the fact.")
w("")
w("---")
w("")
w("## 5. HB126 — what changed, and what it does to any coverage claim")
w("")
w("Verified against the enrolled bill text and the legislature's action history, not against the")
w("Division's summary alone.")
w("")
w("- **HB 126, 34th Alaska Legislature**, version SCS CSHB 126(L&C), short title")
w("  *REINSTATEMENT NATIVE CORPS/ANCSA REPORTS*.")
w("- **CHAPTER 37 SLA 26. Signed into law 6/24/2026. Effective date of law 6/25/26.**")
w("  Section 3: \"This Act takes effect immediately under AS 01.10.070(c).\"")
w("- The DBS notice on the portal root states: \"On June 25, 2026, HB126 became law and changes which")
w("  Alaska Native Claims Settlement Act (ANCSA) Corporations meet the Division's filing requirements")
w("  under AS 45.55.139.\"")
w("")
w("**Section 2 amends AS 45.55.139.** In the enrolled text, bracketed capitals are deletions:")
w("")
w("> A copy of all annual reports, proxies, consents or authorizations, proxy statements, and other")
w("> materials relating to proxy solicitations distributed, published, or made available by any person")
w("> to at least 30 Alaska resident shareholders of a corporation organized under Alaska law under 43")
w("> U.S.C. 1601 et seq. (Alaska Native Claims Settlement Act) **with** [THAT HAS TOTAL ASSETS")
w("> EXCEEDING $1,000,000 AND] a class of equity security held of record by 500 or more **original")
w("> shareholders when the corporation was originally organized** [PERSONS] shall be filed with the")
w("> administrator concurrently with its distribution to shareholders.")
w("")
w("Two changes, both narrowing who files:")
w("")
w("1. **The $1,000,000 total-assets test is deleted outright.**")
w("2. **The 500-holder test is re-anchored in time** — from 500 or more *current* holders of record to")
w("   500 or more *original shareholders at original organisation* under ANCSA.")
w("")
w("The practical effect runs one way: a village corporation whose shareholder roll grew past 500 through")
w("inheritance since 1971, but which enrolled fewer than 500 originally, **is no longer a filer**.")
w("Regional corporations and originally-large village corporations remain filers. So:")
w("")
w("- Any coverage statement built on this source for periods **after 2026-06-25** is coverage of the")
w("  **post-HB126 filer population**, which is smaller than the pre-HB126 population and much smaller")
w("  than the 196-entry roster. Do not express portal coverage as a fraction of the roster without")
w("  saying this.")
w("- Expect the 60-name dropdown to **shrink** in future harvests, and expect some corporations with")
w("  2016–2025 filings to stop appearing. That is a statutory change, not data loss. Re-capture the")
w("  dropdown on every future run and diff it; this run's list is preserved in")
w("  `code/ancsa_portal/corps.json`.")
w("")
w("**Section 1 also matters to the entity spine** even though it is not a filing rule. It amends")
w("AS 10.06.960(k) so an involuntarily dissolved Native village corporation may be reinstated **at any")
w("time**, deleting both the two-year window in AS 10.06.633(e) and the \"on or before December 31, 2020\"")
w("deadline. Reinstated corporations will appear as new or returning entities in the ANC roster.")
w("")
w("---")
w("")
w("## 6. The Division's own caveats, recorded")
w("")
w("Stated by the Division to Elijah and reproduced here so no future run scores them as gaps:")
w("")
w("1. **Filings sit in a queue. Allow ten business days** before concluding a document is missing. The")
w("   Division recommends checking late Friday afternoon. Any document filed in the ten business days")
w("   before 2026-08-05 may therefore be absent from this harvest.")
w("2. **Some corporations will not have annual reports at all**, depending on when their annual meeting")
w("   falls. An absent report is not a missing document.")
w("3. **HB126 changed which corporations meet the filing requirements** — section 5 above.")
w("")
w("---")
w("")
w("## 7. Value traps caught")
w("")
w("Every one of these was present in retrieved text next to a real transaction, and none was written")
w("into a value field.")
w("")
w("1. **Purchase-price allocation totals that look like prices.** Chugach's Rex Electric note ends")
w("   \"Total assets net of liabilities assumed $32,549,086\" — the same number as total consideration by")
w("   construction, not a second figure. Total assets of $54,754,313 in the same table is a balance-sheet")
w("   item.")
w("2. **Fair value of total consideration transferred, when a minority stake was bought.** Sealaska paid")
w("   $17,850,000 for 51% of Odyssey; the note's \"fair value of total consideration transferred\" is")
w("   $35,000,000 because it adds the $17,150,000 fair value of the 49% Sealaska did **not** buy. Same")
w("   pattern at Geo Services ($8,225,000 cash vs $16,128,000 stated total).")
w("3. **Contingent consideration inflating a table figure above the stated price.** ASRC's Brad Cole")
w("   narrative says $15,925,000; the acquisition table says a net purchase price of $32,175,000 because")
w("   it books an estimated $16,250,000 of a potential $24,000,000 earn-out that the filing itself says")
w("   depends on BCC winning a future contract. Same at Hudspeth ($13,000,000 narrative vs $18,500,000")
w("   table).")
w("4. **Revenue contribution quoted next to an acquisition.** ASRC reports that DNC and Vistronix")
w("   \"provided an additional $115.8 million of combined revenues\" and that API \"added $7.3 million of")
w("   revenues\". Those are segment revenue effects, not prices.")
w("5. **Portfolio balances beside a minority investment.** ASRC Capital's minority interest in Pirlo")
w("   Energy Holdings sits two sentences from \"$76.3 million\" of alternative investments and \"$68.8")
w("   million\" of unfunded commitments. No price for Pirlo exists in the filing; the lead was skipped.")
w("6. **Escrow and earn-out deposits.** Aleut's $3,700,000 escrow for the Patrick Mechanical earn-out is")
w("   not the purchase price. ASRC's escrow and holdback amounts are components of prices already")
w("   recorded.")
w("7. **Impairment charges.** ASRC's $10.2 million Trilogy impairment \"to align with the value of the")
w("   purchase price at acquisition\" is a write-down, not consideration, and ASRC was a minority holder.")
w("8. **Balance-sheet effects attributed to a deal.** BSNC's 2016 report attributes a $34 million rise in")
w("   total assets and long-term debt reaching $41 million to the AIH acquisition. The price is")
w("   $65,000,000 and is stated separately.")
w("9. **A corporation contradicting itself.** The Aleut Corporation's own annual reports date the ARS")
w("   International acquisition to *both* June 1, 2013 and June 1, 2014. No row was written. A")
w("   restatement in a later annual report is not independent verification of an earlier one.")
w("")
w("---")
w("")
w("## 8. Skipped leads — %d" % len(skip))
w("")
w("| Reason | Count |")
w("|---|---|")
for k, v in skipr.most_common():
    w("| `%s` | %d |" % (k, v))
w("")
w("The `no_date` entries are almost all year-only or fiscal-year-only statements. The brief's rule was")
w("applied literally: a fiscal year is not a date and nothing was inferred from one. The two most")
w("valuable follow-ups are **Sealaska/Orca Bay (April 1, 2019, exact date, price not in the retrieved")
w("document)** and **CIRI's 2015 buy-out of the remaining 25% of Weldin for $6,000,000 (price exact,")
w("date year-only)** — each needs one more annual report from the index to convert.")
w("")
w("---")
w("")
w("## 9. Retrieval scope and what is still on the table")
w("")
w("%s of the %s indexed documents were downloaded (%.2f GB): every document the per-corporation index" % (format(len(man), ","), format(len(idx), ","), dl_bytes / 1024 ** 3))
w("attributed to one of the twelve **regional** corporations in the `ANCSA Annual Report` category,")
w("2016 through 2026. Village-corporation annual reports and the ~%s proxy documents were indexed but" % format(len(idx) - len(man), ","))
w("not retrieved — indexing is complete, retrieval is deliberately partial, and the index records")
w("`downloaded = no` for every one of them so the boundary is explicit rather than implied.")
w("")
w("**%d of the %d downloaded PDFs are image-only** and yield no extractable text (notably the 2017 CIRI" % (noext, len(man)))
w("and 2017 Calista annual reports, several Doyon settlement-trust reports, and the 2021–2022 Bering")
w("Straits reports). They are archived and hashed, and they are the obvious OCR queue. The 2017 ASRC")
w("annual report is in this group, which is exactly why the ASRC \"Finite\" and \"USC\" 2017 acquisitions")
w("could not be dated.")
w("")
w("Ranked follow-ups:")
w("")
w("1. **OCR the %d image-only PDFs.** Two named ASRC 2017 acquisitions and two 2022 Calista" % noext)
w("   acquisitions are sitting behind them.")
w("2. **Download and mine village-corporation annual reports.** Choggiung, Olgoonik, Kuukpik, Tikigaq,")
w("   Ukpeaġvik, Huna Totem, Goldbelt and Sitnasuak all file, all operate government-contracting")
w("   subsidiaries, and none was retrieved in this run.")
w("3. **Work 2020–2026 systematically.** The mining pass found dated, priced transactions in the 2020+")
w("   reports that were not carried into rows here for time — BBNC's GHEMM/John Burns/CSI/Precision")
w("   table, Sealaska's UK acquisitions (DME Systems, Blue Sea Food, Scantech), CIRI's January 2026 I2X")
w("   and HABCO purchases, and ASRC's 2025 Sigma Science and Applied Research Solutions deals. Each is a")
w("   verifiable row.")
w("4. **Emit ownership-change records.** All %d rows are acquisitions or interest changes and every one" % len(deals))
w("   should feed the time-aware attribution ledger. The Chugach/All American Oilfield pair")
w("   (ANCSA-2015-001 at 90%, ANCSA-2020-001 taking it to 100%) is a complete five-year arc on one")
w("   subsidiary.")
w("5. **Re-harvest after each annual-meeting season**, respecting the ten-business-day queue, and diff")
w("   the corporation dropdown to track the post-HB126 filer population.")
w("6. **Do not mine the proxy corpus for deals.** Use it to seed an ANC governance dataset instead.")
w("")

open(os.path.join(CP, "docs", "ANCSA_PORTAL_BUILD_LOG.md"), "w", encoding="utf-8").write("\n".join(L) + "\n")
print("wrote docs/ANCSA_PORTAL_BUILD_LOG.md", len(L), "lines")
