// Record the manifest's current release of every collection in the ledger,
// data/cedar/releases.json, so a release stays on the record after the
// manifest moves past it.
//
//     node scripts/record-release.mjs          # append what is new
//     node scripts/record-release.mjs --check  # exit 1 if the ledger is behind
//
// WHY A LEDGER
// Codex, PR #51, and it is right: pressReleases.js derived each collection's
// first release from the CURRENT descriptor, so the day the workspace
// re-imports a collection at v1 the v0 entry -- its date, its measured facts,
// its permalink anchor that a citation may already name -- would be recomputed
// as v1 and disappear. Provenance that a re-import can rewrite is not
// provenance. The ledger is append-only: a version, once recorded, keeps the
// facts it was recorded with, and the release feed reads the ledger rather
// than the descriptor for history.
//
// Nothing here is typed. Every field is copied from the manifest at the
// moment the version is recorded, which is the same moment the manifest was
// written. Run this after `scripts/import_cedar_manifest.py`; the tests in
// src/features/grove/pressReleases.test.js fail, naming this command, when the
// manifest carries a version the ledger does not.
//
// A version re-imported with different facts is refused rather than
// overwritten: the ledger's entry for v0 IS v0, and a descriptor that changed
// under the same version needs a new version, not a quieter ledger.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const MANIFEST = join(here, "..", "data", "cedar", "collections.manifest.json");
const LEDGER = join(here, "..", "data", "cedar", "releases.json");

const manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));
let ledger;
try {
  ledger = JSON.parse(readFileSync(LEDGER, "utf8"));
} catch {
  ledger = { note: "", releases: {} };
}
ledger.note =
  "Generated by scripts/record-release.mjs from collections.manifest.json. " +
  "Append-only: every entry is a release the manifest shipped, with the facts " +
  "it shipped with. Never hand-edited.";
ledger.releases ??= {};

/** The facts a release is recorded with, all copied from the manifest. */
export function recordOf(entry) {
  const { descriptor, cedar, sample } = entry;
  return {
    version: descriptor.version,
    date: descriptor.updated,
    tables: cedar.n_tables,
    rowsLabel: descriptor.rows_label,
    preview: sample?.path ? { table: sample.table, rows: sample.rows, of: sample.of } : null,
    blockers: cedar.blockers.length,
  };
}

const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
const check = process.argv.includes("--check");
const problems = [];
let appended = 0;

for (const entry of manifest.collections) {
  const record = recordOf(entry);
  const history = (ledger.releases[entry.id] ??= []);
  const existing = history.find((item) => item.version === record.version);
  if (existing) {
    if (!same(existing, record)) {
      problems.push(
        `${entry.id} ${record.version}: the manifest's facts differ from the ledger's ` +
          `(ledger ${JSON.stringify(existing)}, manifest ${JSON.stringify(record)}). ` +
          "A release that changed needs a new version; the ledger does not overwrite one.",
      );
    }
    continue;
  }
  if (check) {
    problems.push(`${entry.id} ${record.version} is in the manifest and not in the ledger`);
    continue;
  }
  history.push(record);
  appended += 1;
}

if (problems.length) {
  for (const problem of problems) console.error(`  !! ${problem}`);
  process.exit(1);
}
if (!check) {
  writeFileSync(LEDGER, JSON.stringify(ledger, null, 2) + "\n");
  console.log(`  ledger  data/cedar/releases.json  ${appended} release(s) recorded`);
} else {
  console.log("  ledger  data/cedar/releases.json  current");
}
