// Record the manifest's current release of every collection in the ledger,
// data/cedar/releases.json, so a release stays on the record after the
// manifest moves past it.
//
//     node scripts/record-release.mjs          # append what is new
//     node scripts/record-release.mjs --check  # exit 1 if the ledger is behind
//
// WHY A LEDGER
// Codex, PR #51, and it is right: pressReleases.js derived each collection's
// first release from the CURRENT descriptor, so the day the workspace
// re-imports a collection at v1 the v0 entry -- its date, its measured facts,
// its permalink anchor that a citation may already name -- would be recomputed
// as v1 and disappear. Provenance that a re-import can rewrite is not
// provenance. The ledger is append-only: a version, once recorded, keeps the
// facts it was recorded with, and the release feed reads the ledger rather
// than the descriptor for history.
//
// Nothing here is typed. Every field is copied from the manifest at the
// moment the version is recorded, which is the same moment the manifest was
// written. Run this after `scripts/import_cedar_manifest.py`; the release
// tests (pressReleases.test.js) fail, naming this command, when the manifest
// carries a version the ledger does not.
//
// A version re-imported with different facts is refused rather than
// overwritten: the ledger's entry for v0 IS v0, and a descriptor that changed
// under the same version needs a new version, not a quieter ledger.
//
// THE LEDGER IS TRACKED BY FORCE. `.gitignore` excludes `/data/*` as a
// directory (the data workspace is 38 GB), and every file under data/cedar/
// that the site reads is force-added once and tracked from then on. Codex, PR
// #52: the first version of this ledger was written, read by the build, and
// never committed, so `main` could not build. `server/tests/test_collection.py`
// now fails if the ledger is not in the index.
//
// A LEDGER THAT CANNOT BE READ IS NOT AN EMPTY LEDGER. Codex, PR #52: a
// catch-all around the read treated a malformed file as a missing one, and
// would have rebuilt the ledger from the versions currently in the manifest,
// dropping every older release. Only a missing file starts a new ledger;
// anything else stops here. The write is atomic (temp file, then rename), so
// an interrupted write cannot leave that malformed file behind.

import { readFileSync, renameSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const MANIFEST = join(here, "..", "data", "cedar", "collections.manifest.json");
// `--ledger=<path>` points the script at another file. For the tests that
// prove the refusals below fire; production runs never pass it.
const LEDGER =
  process.argv.find((arg) => arg.startsWith("--ledger="))?.slice("--ledger=".length) ??
  join(here, "..", "data", "cedar", "releases.json");

const manifest = JSON.parse(readFileSync(MANIFEST, "utf8"));

const isPlainObject = (value) =>
  value !== null && typeof value === "object" && !Array.isArray(value);

/**
 * A ledger is a plain object whose `releases` is a plain object. Anything
 * else that parses is refused, and so is anything that does not parse.
 * Codex, PR #53: `{}` passed the first version of this check, `releases` was
 * then initialised empty, and a normal run would have overwritten the file
 * with the manifest's current releases alone.
 */
function refuse(reason) {
  console.error(`  !! ${LEDGER} ${reason}`);
  console.error("     Refusing to rebuild it from the manifest: that would drop every release the manifest has moved past.");
  process.exit(1);
}

let ledger;
try {
  ledger = JSON.parse(readFileSync(LEDGER, "utf8"));
} catch (error) {
  if (error?.code !== "ENOENT") refuse(`exists and cannot be read: ${error.message}`);
  ledger = { note: "", releases: {} };
}
if (!isPlainObject(ledger)) refuse("is not a ledger: the root is not an object");
if (!isPlainObject(ledger.releases)) refuse("is not a ledger: it has no `releases` map");
for (const [id, records] of Object.entries(ledger.releases)) {
  if (!Array.isArray(records) || !records.every((record) => isPlainObject(record) && record.version)) {
    refuse(`is not a ledger: the entry for ${id} is not a list of releases`);
  }
}
ledger.note =
  "Generated by scripts/record-release.mjs from collections.manifest.json. " +
  "Append-only: every entry is a release the manifest shipped, with the facts " +
  "it shipped with. Never hand-edited.";

/**
 * The facts a release is recorded with, all copied from the manifest.
 *
 * Blockers are recorded by name, not by count. Codex, PR #52: readiness in
 * this repository is defined by NAMED blockers, and a count let a release
 * whose blockers changed but kept their number pass the same-facts check.
 */
export function recordOf(entry) {
  const { descriptor, cedar, sample } = entry;
  return {
    version: descriptor.version,
    date: descriptor.updated,
    // The name as it shipped, so a release stays legible after the
    // collection leaves the catalog (Codex, PR #53).
    name: descriptor.name,
    tables: cedar.n_tables,
    rowsLabel: descriptor.rows_label,
    preview: sample?.path ? { table: sample.table, rows: sample.rows, of: sample.of } : null,
    blockers: [...cedar.blockers],
  };
}

const same = (a, b) => JSON.stringify(a) === JSON.stringify(b);
const check = process.argv.includes("--check");
const problems = [];
let appended = 0;

for (const entry of manifest.collections) {
  const record = recordOf(entry);
  const history = (ledger.releases[entry.id] ??= []);
  const existing = history.find((item) => item.version === record.version);
  if (existing) {
    if (!same(existing, record)) {
      problems.push(
        `${entry.id} ${record.version}: the manifest's facts differ from the ledger's ` +
          `(ledger ${JSON.stringify(existing)}, manifest ${JSON.stringify(record)}). ` +
          "A release that changed needs a new version; the ledger does not overwrite one.",
      );
    }
    continue;
  }
  if (check) {
    problems.push(`${entry.id} ${record.version} is in the manifest and not in the ledger`);
    continue;
  }
  history.push(record);
  appended += 1;
}

if (problems.length) {
  for (const problem of problems) console.error(`  !! ${problem}`);
  process.exit(1);
}
if (!check) {
  const temp = `${LEDGER}.tmp`;
  writeFileSync(temp, JSON.stringify(ledger, null, 2) + "\n");
  renameSync(temp, LEDGER);
  console.log(`  ledger  data/cedar/releases.json  ${appended} release(s) recorded`);
} else {
  console.log("  ledger  data/cedar/releases.json  current");
}
